// FROG TOWER question bank.
// Q(category, text, correctAnswer, wrong1, wrong2, wrong3, difficulty)
// difficulty: 1 = easy, 2 = medium (default), 3 = hard
// The correct answer is ALWAYS first here; the server shuffles option order per send.
function Q(cat, text, correct, w1, w2, w3, d) {
  return { cat, text, correct, wrong: [w1, w2, w3], d: d || 2 };
}

const QUESTIONS = [
  // ---------------- ANIMALS ----------------
  Q('Animals', 'What is the largest animal to have ever lived?', 'Blue whale', 'African elephant', 'Woolly mammoth', 'Giant squid', 2),
  Q('Animals', 'What is a group of lions called?', 'A pride', 'A pack', 'A herd', 'A flock', 1),
  Q('Animals', 'What is a baby frog called?', 'A tadpole', 'A froglet', 'A polliwink', 'A hatchling', 1),
  Q('Animals', 'What is the fastest land animal?', 'Cheetah', 'Ostrich', 'Pronghorn', 'Greyhound', 1),
  Q('Animals', 'Which of these birds cannot fly?', 'Penguin', 'Swan', 'Owl', 'Falcon', 1),
  Q('Animals', 'How many hearts does an octopus have?', 'Three', 'One', 'Two', 'Five', 3),
  Q('Animals', 'How many legs does a spider have?', 'Eight', 'Six', 'Ten', 'Twelve', 1),
  Q('Animals', 'What is the largest living land animal?', 'African elephant', 'White rhino', 'Hippopotamus', 'Giraffe', 1),
  Q('Animals', 'Which of these animals is a marsupial?', 'Kangaroo', 'Beaver', 'Raccoon', 'Hedgehog', 2),
  Q('Animals', 'What do bees make honey from?', 'Nectar', 'Tree sap', 'Dew', 'Pollen only', 2),
  Q('Animals', 'What is a baby kangaroo called?', 'A joey', 'A cub', 'A kit', 'A calf', 2),
  Q('Animals', 'How many legs does an insect have?', 'Six', 'Four', 'Eight', 'Ten', 1),
  Q('Animals', 'Which animal is called the King of the Jungle?', 'Lion', 'Tiger', 'Gorilla', 'Elephant', 1),
  Q('Animals', 'What color is a polar bear’s skin under its fur?', 'Black', 'White', 'Pink', 'Gray', 3),
  Q('Animals', 'Which sea creature has eight arms?', 'Octopus', 'Starfish', 'Jellyfish', 'Crab', 1),
  Q('Animals', 'What is the tallest animal in the world?', 'Giraffe', 'Elephant', 'Ostrich', 'Camel', 1),
  Q('Animals', 'Which of these animals often sleeps standing up?', 'Horse', 'Dog', 'Cat', 'Pig', 2),
  Q('Animals', 'What is a group of wolves called?', 'A pack', 'A pride', 'A gaggle', 'A swarm', 1),
  Q('Animals', 'Which of these mammals lays eggs?', 'Platypus', 'Bat', 'Dolphin', 'Sloth', 2),
  Q('Animals', 'What do giant pandas mainly eat?', 'Bamboo', 'Fish', 'Ants', 'Berries', 1),
  Q('Animals', 'Which of these animals is the slowest?', 'Sloth', 'Tortoise-eating hare', 'Housecat', 'Chicken', 1),
  Q('Animals', 'Frogs can breathe through their lungs and their what?', 'Skin', 'Ears', 'Feet', 'Tongue', 2),
  Q('Animals', 'What do caterpillars turn into?', 'Butterflies or moths', 'Beetles', 'Dragonflies', 'Grasshoppers', 1),
  Q('Animals', 'What is a baby dog called?', 'A puppy', 'A kitten', 'A cub', 'A foal', 1),
  Q('Animals', 'A frog catches insects using its what?', 'Tongue', 'Claws', 'Tail', 'Wings', 1),
  Q('Animals', 'What is a baby cat called?', 'A kitten', 'A pup', 'A cub', 'A chick', 1),
  Q('Animals', 'What is a baby sheep called?', 'A lamb', 'A kid', 'A calf', 'A fawn', 1),
  Q('Animals', 'What is a baby cow called?', 'A calf', 'A colt', 'A lamb', 'A piglet', 1),
  Q('Animals', 'What is a baby horse called?', 'A foal', 'A calf', 'A cub', 'A joey', 2),
  Q('Animals', 'What is a baby bear called?', 'A cub', 'A pup', 'A kit', 'A whelp', 1),
  Q('Animals', 'What is a baby goat called?', 'A kid', 'A lamb', 'A fawn', 'A billy', 2),
  Q('Animals', 'What is a group of fish called?', 'A school', 'A flock', 'A herd', 'A pack', 1),
  Q('Animals', 'What is a group of crows called?', 'A murder', 'A gaggle', 'A parliament', 'A colony', 3),
  Q('Animals', 'What is a group of bees called?', 'A swarm', 'A cloud', 'A buzz', 'A hive-full', 1),
  Q('Animals', 'What is a group of geese on the ground called?', 'A gaggle', 'A school', 'A pod', 'A pride', 2),
  Q('Animals', 'Which bird is the fastest animal in a dive?', 'Peregrine falcon', 'Golden eagle', 'Swift', 'Osprey', 3),
  Q('Animals', 'What is the largest bird in the world?', 'Ostrich', 'Emu', 'Albatross', 'Condor', 1),
  Q('Animals', 'Which bird is famous for copying human speech?', 'Parrot', 'Pigeon', 'Seagull', 'Sparrow', 1),
  Q('Animals', 'Which bird is the national bird of the USA?', 'Bald eagle', 'Turkey', 'Hawk', 'Raven', 1),
  Q('Animals', 'How many humps does a Bactrian camel have?', 'Two', 'One', 'Three', 'None', 3),
  Q('Animals', 'How many humps does a dromedary camel have?', 'One', 'Two', 'Three', 'None', 3),
  Q('Animals', 'Which big cat has stripes?', 'Tiger', 'Lion', 'Cougar', 'Jaguar', 1),
  Q('Animals', 'Which big cat drags its meal up into trees?', 'Leopard', 'Lion', 'Cheetah', 'Lynx', 3),
  Q('Animals', 'What is the largest living reptile?', 'Saltwater crocodile', 'Komodo dragon', 'Anaconda', 'Galapagos tortoise', 2),
  Q('Animals', 'What is the largest fish in the sea?', 'Whale shark', 'Great white shark', 'Blue marlin', 'Manta ray', 2),
  Q('Animals', 'Which bear lives around the North Pole?', 'Polar bear', 'Grizzly bear', 'Panda', 'Black bear', 1),
  Q('Animals', 'How many legs does a crab have?', 'Ten', 'Six', 'Eight', 'Twelve', 3),
  Q('Animals', 'Snakes smell using their what?', 'Tongue', 'Nostrils', 'Eyes', 'Skin', 2),
  Q('Animals', 'Beavers gnaw down trees to build what?', 'Dams', 'Ladders', 'Rafts', 'Fences', 1),
  Q('Animals', 'What is a female deer called?', 'A doe', 'A mare', 'A ewe', 'A hen', 2),
  Q('Animals', 'What is a male chicken called?', 'A rooster', 'A drake', 'A gander', 'A stallion', 1),
  Q('Animals', 'What is a female chicken called?', 'A hen', 'A doe', 'A sow', 'A nanny', 1),
  Q('Animals', 'What is a group of puppies born together called?', 'A litter', 'A batch', 'A brood', 'A clutch', 1),
  Q('Animals', 'Owls are mostly active at what time?', 'Night', 'Morning', 'Noon', 'Sunset only', 1),
  Q('Animals', 'What do you call animals that are active at night?', 'Nocturnal', 'Diurnal', 'Dormant', 'Migratory', 2),
  Q('Animals', 'Which animal is famous for playing dead?', 'Opossum', 'Raccoon', 'Badger', 'Porcupine', 2),
  Q('Animals', 'Which animal sprays a terrible smell to defend itself?', 'Skunk', 'Ferret', 'Mole', 'Armadillo', 1),
  Q('Animals', 'Which lizard changes color to blend in?', 'Chameleon', 'Gecko', 'Iguana', 'Skink', 1),
  Q('Animals', 'How many arms does a starfish usually have?', 'Five', 'Four', 'Six', 'Eight', 2),
  Q('Animals', 'Dolphins are what kind of animal?', 'Mammals', 'Fish', 'Amphibians', 'Reptiles', 2),
  Q('Animals', 'A shark’s skeleton is made of what?', 'Cartilage', 'Bone', 'Shell', 'Keratin', 3),
  Q('Animals', 'What do spiders spin their webs from?', 'Silk', 'Cotton', 'Slime', 'Hair', 1),
  Q('Animals', 'A honeybee dies after doing what?', 'Stinging', 'Dancing', 'Flying in rain', 'Making honey', 2),
  Q('Animals', 'Which insect glows at night?', 'Firefly', 'Dragonfly', 'Moth', 'Cricket', 1),
  Q('Animals', 'Which tiny insect can carry many times its own body weight?', 'Ant', 'Fly', 'Mosquito', 'Ladybug', 1),
  Q('Animals', 'What is the only mammal that can truly fly?', 'Bat', 'Flying squirrel', 'Sugar glider', 'Colugo', 2),
  Q('Animals', 'Which African animal’s name means “river horse”?', 'Hippopotamus', 'Rhinoceros', 'Wildebeest', 'Buffalo', 3),
  Q('Animals', 'Which striped animal’s pattern is unique to each individual?', 'Zebra', 'Skunk', 'Badger', 'Raccoon', 2),
  Q('Animals', 'What is the largest primate?', 'Gorilla', 'Orangutan', 'Chimpanzee', 'Baboon', 2),
  Q('Animals', 'Which ape shares the most DNA with humans?', 'Chimpanzee', 'Gorilla', 'Gibbon', 'Orangutan', 2),
  Q('Animals', 'An elephant grabs things with its what?', 'Trunk', 'Tusks', 'Ears', 'Tail', 1),
  Q('Animals', 'Which sea creature can regrow a lost arm?', 'Starfish', 'Crab', 'Seahorse', 'Eel', 2),
  Q('Animals', 'A rhino’s horn is made of the same material as what?', 'Fingernails', 'Teeth', 'Bone', 'Wood', 3),
  Q('Animals', 'Which flightless bird lives in New Zealand?', 'Kiwi', 'Puffin', 'Dodo', 'Roadrunner', 2),
  Q('Animals', 'Which Australian bird is known for its laughing call?', 'Kookaburra', 'Cockatoo', 'Lyrebird', 'Magpie', 3),
  Q('Animals', 'What is the largest species of penguin?', 'Emperor penguin', 'King penguin', 'Rockhopper', 'Adelie', 2),
  Q('Animals', 'Which slow creature leaves a slime trail?', 'Snail', 'Worm', 'Caterpillar', 'Beetle', 1),
  Q('Animals', 'What is a fox’s home called?', 'A den', 'A nest', 'A lodge', 'A roost', 2),
  Q('Animals', 'What is a rabbit’s underground home called?', 'A burrow', 'A den', 'A hollow', 'A mound', 2),
  Q('Animals', 'What is an eagle’s nest called?', 'An aerie', 'A roost', 'A perch', 'A coop', 3),
  Q('Animals', 'Which bird is a symbol of peace?', 'Dove', 'Swan', 'Crane', 'Robin', 1),
  Q('Animals', 'Which animal is called man’s best friend?', 'Dog', 'Cat', 'Horse', 'Parrot', 1),
  Q('Animals', 'What do camels store in their humps?', 'Fat', 'Water', 'Food', 'Air', 3),
  Q('Animals', 'Which whale has a long spiral tusk?', 'Narwhal', 'Beluga', 'Orca', 'Humpback', 2),
  Q('Animals', 'What do woodpeckers hammer holes into?', 'Trees', 'Rocks', 'Sand', 'Fences', 1),

  // ---------------- SCIENCE ----------------
  Q('Science', 'What is H2O better known as?', 'Water', 'Salt', 'Oxygen', 'Hydrogen peroxide', 1),
  Q('Science', 'Which element has the chemical symbol Au?', 'Gold', 'Silver', 'Aluminum', 'Copper', 3),
  Q('Science', 'What is the closest star to Earth?', 'The Sun', 'Alpha Centauri', 'Polaris', 'Sirius', 1),
  Q('Science', 'What force pulls objects toward the Earth?', 'Gravity', 'Magnetism', 'Friction', 'Inertia', 1),
  Q('Science', 'What is the largest organ of the human body?', 'Skin', 'Liver', 'Brain', 'Lungs', 2),
  Q('Science', 'How many bones does an adult human have?', '206', '106', '306', '250', 3),
  Q('Science', 'Which gas do plants absorb from the air?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Helium', 2),
  Q('Science', 'Roughly how fast does light travel?', '300,000 km per second', '300 km per second', '3,000 km per second', '30,000 km per hour', 3),
  Q('Science', 'What is the center of an atom called?', 'The nucleus', 'The core', 'The proton', 'The shell', 2),
  Q('Science', 'Which element has the symbol O?', 'Oxygen', 'Osmium', 'Gold', 'Iron', 1),
  Q('Science', 'At what temperature does water boil at sea level?', '100°C', '90°C', '110°C', '120°C', 2),
  Q('Science', 'At what temperature does water freeze?', '0°C', '10°C', '-10°C', '5°C', 1),
  Q('Science', 'Which of these is NOT a state of matter?', 'Energy', 'Solid', 'Liquid', 'Gas', 2),
  Q('Science', 'What shape is a DNA molecule?', 'A double helix', 'A sphere', 'A cube', 'A flat ribbon', 2),
  Q('Science', 'Animals that eat only plants are called what?', 'Herbivores', 'Carnivores', 'Omnivores', 'Insectivores', 1),
  Q('Science', 'Which metal is liquid at room temperature?', 'Mercury', 'Lead', 'Tin', 'Sodium', 3),
  Q('Science', 'Which part of an animal cell contains its DNA?', 'The nucleus', 'The cell wall', 'The mitochondria', 'The cytoplasm', 2),
  Q('Science', 'What is the hardest natural substance on Earth?', 'Diamond', 'Granite', 'Steel', 'Quartz', 1),
  Q('Science', 'Which gas do humans need to breathe to survive?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen', 1),
  Q('Science', 'What is the unit of electrical current?', 'Ampere', 'Volt', 'Watt', 'Ohm', 3),
  Q('Science', 'What does a thermometer measure?', 'Temperature', 'Pressure', 'Humidity', 'Wind speed', 1),
  Q('Science', 'Which vitamin does your body make from sunlight?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B12', 2),
  Q('Science', 'Sound travels fastest through which of these?', 'Steel', 'Air', 'Water', 'A vacuum', 3),
  Q('Science', 'What kind of animal is a frog?', 'An amphibian', 'A reptile', 'A mammal', 'A fish', 1),
  Q('Science', 'Which element has the symbol Fe?', 'Iron', 'Fluorine', 'Iridium', 'Francium', 3),
  Q('Science', 'Which element has the symbol Na?', 'Sodium', 'Nitrogen', 'Neon', 'Nickel', 3),
  Q('Science', 'Which element has the symbol He?', 'Helium', 'Hydrogen', 'Hafnium', 'Mercury', 2),
  Q('Science', 'Which element has the symbol H?', 'Hydrogen', 'Helium', 'Hassium', 'Holmium', 1),
  Q('Science', 'Which element has the symbol C?', 'Carbon', 'Calcium', 'Copper', 'Chlorine', 2),
  Q('Science', 'What is the most abundant gas in Earth’s atmosphere?', 'Nitrogen', 'Oxygen', 'Carbon dioxide', 'Argon', 3),
  Q('Science', 'What gas do plants release during photosynthesis?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Methane', 2),
  Q('Science', 'What process lets plants make food from sunlight?', 'Photosynthesis', 'Respiration', 'Fermentation', 'Digestion', 1),
  Q('Science', 'A seesaw is an example of which simple machine?', 'Lever', 'Pulley', 'Wheel and axle', 'Screw', 2),
  Q('Science', 'A ramp is an example of which simple machine?', 'Inclined plane', 'Lever', 'Wedge', 'Pulley', 2),
  Q('Science', 'What kind of energy does a moving object have?', 'Kinetic energy', 'Potential energy', 'Thermal energy', 'Chemical energy', 2),
  Q('Science', 'What is stored energy called?', 'Potential energy', 'Kinetic energy', 'Sound energy', 'Solar energy', 2),
  Q('Science', 'At what Fahrenheit temperature does water boil at sea level?', '212°F', '100°F', '180°F', '250°F', 3),
  Q('Science', 'At what Fahrenheit temperature does water freeze?', '32°F', '0°F', '20°F', '40°F', 2),
  Q('Science', 'What state of matter is steam?', 'Gas', 'Liquid', 'Solid', 'Plasma', 1),
  Q('Science', 'What instrument measures air pressure?', 'Barometer', 'Thermometer', 'Odometer', 'Hygrometer', 3),
  Q('Science', 'What instrument measures wind speed?', 'Anemometer', 'Barometer', 'Altimeter', 'Speedometer', 3),
  Q('Science', 'What is molten rock called while still underground?', 'Magma', 'Lava', 'Ash', 'Obsidian', 2),
  Q('Science', 'What is molten rock called once it erupts?', 'Lava', 'Magma', 'Basalt', 'Pumice', 1),
  Q('Science', 'Scientists who study rocks are called what?', 'Geologists', 'Biologists', 'Chemists', 'Botanists', 2),
  Q('Science', 'Scientists who study weather are called what?', 'Meteorologists', 'Astronomers', 'Ecologists', 'Physicists', 2),
  Q('Science', 'Scientists who study stars and planets are called what?', 'Astronomers', 'Astrologers', 'Geographers', 'Archaeologists', 1),
  Q('Science', 'What is the smallest unit of a chemical element?', 'An atom', 'A molecule', 'A cell', 'A proton', 2),
  Q('Science', 'What do two or more bonded atoms form?', 'A molecule', 'A nucleus', 'An ion cloud', 'A crystal only', 2),
  Q('Science', 'What electric charge does an electron carry?', 'Negative', 'Positive', 'Neutral', 'Double positive', 2),
  Q('Science', 'What electric charge does a proton carry?', 'Positive', 'Negative', 'Neutral', 'It changes', 2),
  Q('Science', 'Which particle in an atom has no charge?', 'Neutron', 'Proton', 'Electron', 'Photon', 2),
  Q('Science', 'What is the chemical formula for table salt?', 'NaCl', 'H2O', 'CO2', 'KCl', 3),
  Q('Science', 'The Richter scale measures the strength of what?', 'Earthquakes', 'Hurricanes', 'Tornadoes', 'Floods', 2),
  Q('Science', 'What kind of energy comes directly from the sun?', 'Solar energy', 'Nuclear energy', 'Wind energy', 'Coal power', 1),
  Q('Science', 'What is it called when liquid water turns into vapor?', 'Evaporation', 'Condensation', 'Precipitation', 'Sublimation', 2),
  Q('Science', 'What is it called when vapor turns back into liquid?', 'Condensation', 'Evaporation', 'Freezing', 'Melting', 2),
  Q('Science', 'What is rain, snow, and hail collectively called?', 'Precipitation', 'Condensation', 'Humidity', 'Saturation', 2),
  Q('Science', 'What type of rock forms from cooled lava?', 'Igneous', 'Sedimentary', 'Metamorphic', 'Fossil rock', 3),
  Q('Science', 'What type of rock forms in layers from pressed sediment?', 'Sedimentary', 'Igneous', 'Metamorphic', 'Volcanic', 3),
  Q('Science', 'Coal, oil, and natural gas are examples of what?', 'Fossil fuels', 'Renewables', 'Minerals', 'Biofuels', 1),
  Q('Science', 'Magnets most strongly attract which metal?', 'Iron', 'Aluminum', 'Copper', 'Gold', 2),
  Q('Science', 'What are the two poles of a magnet called?', 'North and south', 'East and west', 'Plus and minus', 'Up and down', 1),
  Q('Science', 'What is the study of living things called?', 'Biology', 'Geology', 'Astronomy', 'Meteorology', 1),
  Q('Science', 'What is the study of matter, energy, and motion called?', 'Physics', 'Chemistry', 'Biology', 'Ecology', 2),
  Q('Science', 'What is the study of substances and their reactions called?', 'Chemistry', 'Physics', 'Zoology', 'Botany', 2),
  Q('Science', 'What tiny organism makes bread dough rise?', 'Yeast', 'Mold', 'Algae', 'Bacteria only', 2),
  Q('Science', 'What is frozen carbon dioxide commonly called?', 'Dry ice', 'Black ice', 'Permafrost', 'Glacier ice', 2),
  Q('Science', 'Which gas makes soda drinks fizzy?', 'Carbon dioxide', 'Oxygen', 'Helium', 'Nitrogen', 2),
  Q('Science', 'Animals that eat both plants and meat are called what?', 'Omnivores', 'Herbivores', 'Carnivores', 'Scavengers', 2),
  Q('Science', 'Animals that eat only meat are called what?', 'Carnivores', 'Omnivores', 'Herbivores', 'Insectivores', 1),
  Q('Science', 'What is a young plant that sprouts from a seed called?', 'A seedling', 'A bulb', 'A spore', 'A bud', 1),
  Q('Science', 'Which part of a flowering plant makes the seeds?', 'The flower', 'The roots', 'The stem', 'The bark', 2),
  Q('Science', 'Which part of a plant absorbs water from the soil?', 'The roots', 'The leaves', 'The petals', 'The trunk', 1),
  Q('Science', 'What force slows a sled sliding across snow?', 'Friction', 'Gravity', 'Magnetism', 'Momentum', 2),
  Q('Science', 'What is H2O2 commonly known as?', 'Hydrogen peroxide', 'Heavy water', 'Salt water', 'Ammonia', 3),
  Q('Science', 'What natural satellite creates most of Earth’s tides?', 'The Moon', 'The Sun', 'Venus', 'Jupiter', 2),
  Q('Science', 'What do we call an animal without a backbone?', 'Invertebrate', 'Vertebrate', 'Amphibian', 'Primate', 2),
  Q('Science', 'What is the name for a scientist’s testable prediction?', 'A hypothesis', 'A theory', 'A law', 'A guess-proof', 2),
  Q('Science', 'What lab tool do you look through to magnify slides?', 'Microscope', 'Telescope', 'Periscope', 'Kaleidoscope', 1),

  // ---------------- GEOGRAPHY ----------------
  Q('Geography', 'What is the largest ocean on Earth?', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 1),
  Q('Geography', 'What is the capital of France?', 'Paris', 'Lyon', 'Marseille', 'Nice', 1),
  Q('Geography', 'What is the capital of Japan?', 'Tokyo', 'Osaka', 'Kyoto', 'Hiroshima', 1),
  Q('Geography', 'What is the largest country by area?', 'Russia', 'Canada', 'China', 'USA', 2),
  Q('Geography', 'What is the smallest country in the world?', 'Vatican City', 'Monaco', 'Malta', 'Liechtenstein', 2),
  Q('Geography', 'How many continents are there?', 'Seven', 'Five', 'Six', 'Eight', 1),
  Q('Geography', 'On which continent is the Sahara Desert?', 'Africa', 'Asia', 'Australia', 'South America', 1),
  Q('Geography', 'What is the capital of Australia?', 'Canberra', 'Sydney', 'Melbourne', 'Perth', 3),
  Q('Geography', 'Which country is shaped like a boot?', 'Italy', 'Spain', 'Chile', 'Portugal', 1),
  Q('Geography', 'Mount Everest is part of which mountain range?', 'The Himalayas', 'The Andes', 'The Alps', 'The Rockies', 2),
  Q('Geography', 'Which US state is the largest by area?', 'Alaska', 'Texas', 'California', 'Montana', 2),
  Q('Geography', 'The Great Barrier Reef is off the coast of which country?', 'Australia', 'Brazil', 'Mexico', 'Indonesia', 1),
  Q('Geography', 'What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal', 3),
  Q('Geography', 'Which continent is the coldest?', 'Antarctica', 'Europe', 'North America', 'Asia', 1),
  Q('Geography', 'Most of the Amazon rainforest is in which country?', 'Brazil', 'Peru', 'Colombia', 'Venezuela', 2),
  Q('Geography', 'What is the capital of Italy?', 'Rome', 'Milan', 'Venice', 'Naples', 1),
  Q('Geography', 'Which country has the largest population?', 'India', 'China', 'USA', 'Indonesia', 2),
  Q('Geography', 'Niagara Falls sits on the border of the USA and which country?', 'Canada', 'Mexico', 'Greenland', 'Cuba', 1),
  Q('Geography', 'Which ocean lies between Africa and Australia?', 'Indian Ocean', 'Atlantic Ocean', 'Pacific Ocean', 'Southern Ocean', 2),
  Q('Geography', 'Which river flows through Egypt?', 'The Nile', 'The Amazon', 'The Danube', 'The Ganges', 1),
  Q('Geography', 'What is the capital of Spain?', 'Madrid', 'Barcelona', 'Seville', 'Valencia', 2),
  Q('Geography', 'Which country gave the Statue of Liberty to the USA?', 'France', 'England', 'Italy', 'Spain', 2),
  Q('Geography', 'The Alps are located on which continent?', 'Europe', 'Asia', 'South America', 'North America', 1),
  Q('Geography', 'What is the largest hot desert in the world?', 'The Sahara', 'The Gobi', 'The Mojave', 'The Kalahari', 1),
  Q('Geography', 'What is the capital of Germany?', 'Berlin', 'Munich', 'Frankfurt', 'Hamburg', 1),
  Q('Geography', 'Which US city is nicknamed The Big Apple?', 'New York City', 'Chicago', 'Los Angeles', 'Boston', 1),
  Q('Geography', 'What is the capital of England?', 'London', 'Manchester', 'Birmingham', 'Leeds', 1),
  Q('Geography', 'What is the capital of the United States?', 'Washington, D.C.', 'New York City', 'Los Angeles', 'Chicago', 1),
  Q('Geography', 'What is the capital of Russia?', 'Moscow', 'Saint Petersburg', 'Kiev', 'Minsk', 2),
  Q('Geography', 'What is the capital of China?', 'Beijing', 'Shanghai', 'Hong Kong', 'Shenzhen', 2),
  Q('Geography', 'What is the capital of Egypt?', 'Cairo', 'Alexandria', 'Giza', 'Luxor', 2),
  Q('Geography', 'What is the capital of Greece?', 'Athens', 'Sparta', 'Thessaloniki', 'Crete', 2),
  Q('Geography', 'What is the capital of Ireland?', 'Dublin', 'Belfast', 'Cork', 'Galway', 2),
  Q('Geography', 'What is the capital of Portugal?', 'Lisbon', 'Porto', 'Madrid', 'Faro', 2),
  Q('Geography', 'What is the capital of Austria?', 'Vienna', 'Salzburg', 'Zurich', 'Graz', 2),
  Q('Geography', 'What is the capital of the Netherlands?', 'Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 2),
  Q('Geography', 'What is the capital of Sweden?', 'Stockholm', 'Oslo', 'Gothenburg', 'Copenhagen', 2),
  Q('Geography', 'What is the capital of Norway?', 'Oslo', 'Bergen', 'Stockholm', 'Helsinki', 2),
  Q('Geography', 'What is the capital of Poland?', 'Warsaw', 'Krakow', 'Gdansk', 'Prague', 2),
  Q('Geography', 'What is the capital of New Zealand?', 'Wellington', 'Auckland', 'Christchurch', 'Queenstown', 3),
  Q('Geography', 'What is the capital of Brazil?', 'Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador', 3),
  Q('Geography', 'What is the capital of Argentina?', 'Buenos Aires', 'Santiago', 'Córdoba', 'Montevideo', 2),
  Q('Geography', 'What is the capital of South Korea?', 'Seoul', 'Busan', 'Incheon', 'Pyongyang', 2),
  Q('Geography', 'What is the capital of Thailand?', 'Bangkok', 'Phuket', 'Chiang Mai', 'Hanoi', 2),
  Q('Geography', 'What is the capital of Kenya?', 'Nairobi', 'Mombasa', 'Kampala', 'Lagos', 3),
  Q('Geography', 'What is the capital of Cuba?', 'Havana', 'Santiago de Cuba', 'San Juan', 'Kingston', 2),
  Q('Geography', 'What is the longest river in South America?', 'The Amazon', 'The Paraná', 'The Orinoco', 'The Magdalena', 1),
  Q('Geography', 'What is the largest freshwater lake by surface area?', 'Lake Superior', 'Lake Victoria', 'Lake Michigan', 'Lake Baikal', 3),
  Q('Geography', 'Which US state is a chain of islands in the Pacific?', 'Hawaii', 'Alaska', 'Florida', 'California', 1),
  Q('Geography', 'Which two continents does Russia span?', 'Europe and Asia', 'Asia and North America', 'Europe and Africa', 'Asia only', 2),
  Q('Geography', 'What is the largest island in the world?', 'Greenland', 'Madagascar', 'Borneo', 'New Guinea', 2),
  Q('Geography', 'Which desert stretches across Mongolia and China?', 'The Gobi', 'The Sahara', 'The Kalahari', 'The Outback', 2),
  Q('Geography', 'What is the longest mountain range on land?', 'The Andes', 'The Rockies', 'The Himalayas', 'The Urals', 3),
  Q('Geography', 'The Grand Canyon is in which US state?', 'Arizona', 'Nevada', 'Utah', 'Colorado', 2),
  Q('Geography', 'Which river flows through London?', 'The Thames', 'The Severn', 'The Mersey', 'The Clyde', 2),
  Q('Geography', 'Which river flows through Paris?', 'The Seine', 'The Loire', 'The Rhone', 'The Rhine', 2),
  Q('Geography', 'Mount Fuji is in which country?', 'Japan', 'China', 'South Korea', 'Vietnam', 1),
  Q('Geography', 'Which country is both a country and a continent?', 'Australia', 'Greenland', 'India', 'Madagascar', 1),
  Q('Geography', 'What imaginary line divides Earth into north and south halves?', 'The equator', 'The prime meridian', 'The tropic line', 'The date line', 1),
  Q('Geography', 'Which tropic line lies north of the equator?', 'Tropic of Cancer', 'Tropic of Capricorn', 'The Arctic Circle', 'The prime meridian', 3),
  Q('Geography', 'What is the imaginary line at zero degrees longitude?', 'The prime meridian', 'The equator', 'The date line', 'The polar axis', 3),
  Q('Geography', 'Which ocean is the smallest?', 'Arctic Ocean', 'Indian Ocean', 'Atlantic Ocean', 'Southern Ocean', 2),
  Q('Geography', 'In which salty sea can you float without trying?', 'The Dead Sea', 'The Red Sea', 'The Black Sea', 'The Baltic Sea', 2),
  Q('Geography', 'What is the tallest mountain above sea level?', 'Mount Everest', 'K2', 'Kilimanjaro', 'Denali', 1),
  Q('Geography', 'Which country has a maple leaf on its flag?', 'Canada', 'Sweden', 'Switzerland', 'Norway', 1),
  Q('Geography', 'Which country’s flag shows 50 stars?', 'USA', 'Australia', 'Brazil', 'Chile', 1),
  Q('Geography', 'Which country’s flag is a red circle on white?', 'Japan', 'South Korea', 'China', 'Vietnam', 1),
  Q('Geography', 'Which long, thin country runs down South America’s west coast?', 'Chile', 'Peru', 'Ecuador', 'Uruguay', 2),
  Q('Geography', 'What is the capital of Scotland?', 'Edinburgh', 'Glasgow', 'Aberdeen', 'Dundee', 2),
  Q('Geography', 'Victoria Falls sits on the border of Zimbabwe and which country?', 'Zambia', 'Kenya', 'Tanzania', 'Botswana', 3),
  Q('Geography', 'What is the world’s highest waterfall?', 'Angel Falls', 'Niagara Falls', 'Victoria Falls', 'Iguazu Falls', 3),
  Q('Geography', 'Which mountains traditionally separate Europe and Asia?', 'The Urals', 'The Alps', 'The Caucasus only', 'The Pyrenees', 3),
  Q('Geography', 'Which Italian city is famous for its canals?', 'Venice', 'Florence', 'Milan', 'Naples', 1),
  Q('Geography', 'The Taj Mahal is in which country?', 'India', 'Pakistan', 'Bangladesh', 'Nepal', 1),
  Q('Geography', 'Machu Picchu is in which country?', 'Peru', 'Bolivia', 'Chile', 'Mexico', 2),
  Q('Geography', 'Stonehenge is in which country?', 'England', 'Ireland', 'Scotland', 'France', 2),
  Q('Geography', 'The Leaning Tower is in which Italian city?', 'Pisa', 'Rome', 'Venice', 'Turin', 2),
  Q('Geography', 'Which desert is the driest place on Earth?', 'The Atacama', 'The Sahara', 'The Mojave', 'The Gobi', 3),
  Q('Geography', 'What do you call land completely surrounded by water?', 'An island', 'A peninsula', 'A cape', 'An isthmus', 1),
  Q('Geography', 'What do you call land surrounded by water on three sides?', 'A peninsula', 'An island', 'A delta', 'A plateau', 2),
  Q('Geography', 'What is a narrow strip of land joining two larger land areas?', 'An isthmus', 'A strait', 'A fjord', 'A mesa', 3),
  Q('Geography', 'What is the top of a mountain called?', 'The summit', 'The ridge', 'The base', 'The plateau', 1),
  Q('Geography', 'What is a low stretch of land between mountains called?', 'A valley', 'A canyon rim', 'A mesa', 'A dune', 1),
  Q('Geography', 'What giant wave can be caused by an undersea earthquake?', 'A tsunami', 'A ripple', 'A monsoon', 'A whirlpool', 1),
  Q('Geography', 'Which hemisphere is Australia located in?', 'The Southern Hemisphere', 'The Northern Hemisphere', 'The Western only', 'Neither', 1),
  Q('Geography', 'How many states make up the USA?', '50', '48', '51', '52', 1),

  // ---------------- HISTORY ----------------
  Q('History', 'Who was the first President of the United States?', 'George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'John Adams', 1),
  Q('History', 'In what year did the Titanic sink?', '1912', '1905', '1920', '1898', 2),
  Q('History', 'In what year did World War II end?', '1945', '1939', '1942', '1950', 2),
  Q('History', 'Which ancient civilization built the pyramids of Giza?', 'The Egyptians', 'The Romans', 'The Greeks', 'The Aztecs', 1),
  Q('History', 'Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Vincent van Gogh', 'Pablo Picasso', 1),
  Q('History', 'The Great Wall is located in which country?', 'China', 'Japan', 'India', 'Mongolia', 1),
  Q('History', 'What language did the ancient Romans speak?', 'Latin', 'Greek', 'Italian', 'Hebrew', 2),
  Q('History', 'Who described gravity after famously seeing an apple fall?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Charles Darwin', 1),
  Q('History', 'In which country were the first Olympic Games held?', 'Greece', 'Italy', 'Egypt', 'France', 1),
  Q('History', 'Which Egyptian queen was famous for her ties to Rome?', 'Cleopatra', 'Nefertiti', 'Isis', 'Hatshepsut', 2),
  Q('History', 'The Vikings originally came from which region?', 'Scandinavia', 'Germany', 'Russia', 'Scotland', 2),
  Q('History', 'Which ship carried the Pilgrims to America in 1620?', 'The Mayflower', 'The Santa Maria', 'The Endeavour', 'The Beagle', 2),
  Q('History', 'Who invented the telephone?', 'Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Samuel Morse', 2),
  Q('History', 'Which inventor is famous for the practical light bulb?', 'Thomas Edison', 'Benjamin Franklin', 'Alexander Bell', 'Henry Ford', 1),
  Q('History', 'Gladiators fought in the Colosseum in which city?', 'Rome', 'Athens', 'Cairo', 'Istanbul', 1),
  Q('History', 'In what year did the Berlin Wall fall?', '1989', '1979', '1991', '1985', 3),
  Q('History', 'Knights in the Middle Ages wore suits of what?', 'Armor', 'Silk', 'Wool', 'Leather only', 1),
  Q('History', 'Which country did ninjas and samurai come from?', 'Japan', 'China', 'Korea', 'Thailand', 1),
  Q('History', 'Whose huge signature stands out on the Declaration of Independence?', 'John Hancock', 'Ben Franklin', 'Thomas Jefferson', 'John Adams', 3),
  Q('History', 'In which year did World War I begin?', '1914', '1912', '1918', '1920', 2),
  Q('History', 'In which year did World War I end?', '1918', '1914', '1917', '1921', 3),
  Q('History', 'In which year did World War II begin?', '1939', '1936', '1941', '1943', 2),
  Q('History', 'Who was Britain’s prime minister for most of World War II?', 'Winston Churchill', 'Neville Chamberlain', 'Clement Attlee', 'David Lloyd George', 2),
  Q('History', 'Who was US president during the Civil War?', 'Abraham Lincoln', 'Ulysses S. Grant', 'Andrew Johnson', 'James Buchanan', 2),
  Q('History', 'Who was the boy king of ancient Egypt?', 'Tutankhamun', 'Ramses II', 'Khufu', 'Akhenaten', 2),
  Q('History', 'Which empire built straight roads all across Europe?', 'The Roman Empire', 'The Greek Empire', 'The Persian Empire', 'The Ottoman Empire', 2),
  Q('History', 'Who marched elephants over the Alps to attack Rome?', 'Hannibal', 'Alexander the Great', 'Attila', 'Genghis Khan', 3),
  Q('History', 'Who was the first Roman emperor?', 'Augustus', 'Julius Caesar', 'Nero', 'Constantine', 3),
  Q('History', '“Beware the ___ of March” warned Julius Caesar. Which word fits?', 'Ides', 'Winds', 'Kings', 'Gods', 3),
  Q('History', 'Which explorer reached the Americas in 1492?', 'Christopher Columbus', 'Ferdinand Magellan', 'Marco Polo', 'James Cook', 1),
  Q('History', 'Whose expedition was the first to sail around the world?', 'Ferdinand Magellan’s', 'Columbus’s', 'Drake’s', 'Vespucci’s', 3),
  Q('History', 'Which country did Napoleon lead?', 'France', 'Italy', 'Spain', 'Austria', 1),
  Q('History', 'At which battle was Napoleon finally defeated in 1815?', 'Waterloo', 'Trafalgar', 'Austerlitz', 'Leipzig', 3),
  Q('History', 'Which British queen reigned for most of the 1800s?', 'Queen Victoria', 'Queen Elizabeth I', 'Queen Anne', 'Queen Mary', 2),
  Q('History', 'Which English king famously had six wives?', 'Henry VIII', 'Richard III', 'Edward IV', 'George III', 2),
  Q('History', 'What was the deadly medieval plague called?', 'The Black Death', 'The Red Fever', 'The Great Pox', 'The Sweating End', 1),
  Q('History', 'Which US war was fought between the North and the South?', 'The Civil War', 'The Revolutionary War', 'The War of 1812', 'The Mexican War', 1),
  Q('History', 'What picture-writing did ancient Egyptians use?', 'Hieroglyphics', 'Cuneiform', 'Runes', 'Calligraphy', 2),
  Q('History', 'What paper-like material did Egyptians write on?', 'Papyrus', 'Parchment', 'Bamboo', 'Clay only', 2),
  Q('History', 'Which civilization built Machu Picchu?', 'The Inca', 'The Maya', 'The Aztec', 'The Olmec', 2),
  Q('History', 'Which civilization built Chichen Itza?', 'The Maya', 'The Inca', 'The Aztec', 'The Toltec only', 3),
  Q('History', 'Montezuma ruled which civilization?', 'The Aztec', 'The Inca', 'The Maya', 'The Zapotec', 3),
  Q('History', 'Who invented the movable-type printing press in Europe?', 'Johannes Gutenberg', 'Isaac Newton', 'Leonardo da Vinci', 'Galileo', 2),
  Q('History', 'Who wrote about evolution by natural selection?', 'Charles Darwin', 'Gregor Mendel', 'Louis Pasteur', 'Alfred Wallace only', 2),
  Q('History', 'Who discovered penicillin?', 'Alexander Fleming', 'Marie Curie', 'Joseph Lister', 'Edward Jenner', 3),
  Q('History', 'Who was the first woman to win a Nobel Prize?', 'Marie Curie', 'Florence Nightingale', 'Ada Lovelace', 'Jane Goodall', 2),
  Q('History', 'Who made the first solo flight across the Atlantic?', 'Charles Lindbergh', 'Amelia Earhart', 'The Wright brothers', 'Howard Hughes', 3),
  Q('History', 'Who was the first woman to fly solo across the Atlantic?', 'Amelia Earhart', 'Bessie Coleman', 'Harriet Quimby', 'Valentina Tereshkova', 2),
  Q('History', 'In which year did humans first walk on the moon?', '1969', '1965', '1972', '1959', 2),
  Q('History', 'Which country launched Sputnik, the first satellite?', 'The Soviet Union', 'The USA', 'China', 'Germany', 2),
  Q('History', 'Who was the first human in space?', 'Yuri Gagarin', 'Neil Armstrong', 'Alan Shepard', 'John Glenn', 2),
  Q('History', 'What did the Titanic strike before sinking?', 'An iceberg', 'A reef', 'Another ship', 'A whale', 1),
  Q('History', 'The trick with a giant wooden horse ended which war?', 'The Trojan War', 'The Punic Wars', 'The Persian War', 'The Hundred Years War', 2),
  Q('History', 'Which legendary king held court at a round table?', 'King Arthur', 'King Richard', 'King Alfred', 'King Harold', 1),
  Q('History', 'Which document did King John seal in 1215?', 'The Magna Carta', 'The Domesday Book', 'The Bill of Rights', 'The Round Charter', 3),
  Q('History', 'What was the pirate skull-and-crossbones flag called?', 'The Jolly Roger', 'The Black Mark', 'The Crossbones Cloth', 'The Sea Devil', 2),
  Q('History', 'Rosa Parks made history by keeping her seat on a what?', 'Bus', 'Train', 'Plane', 'Ferry', 1),
  Q('History', 'Who gave the famous “I Have a Dream” speech?', 'Martin Luther King Jr.', 'Malcolm X', 'Frederick Douglass', 'John Lewis', 1),
  Q('History', 'Who became South Africa’s first Black president?', 'Nelson Mandela', 'Desmond Tutu', 'Kofi Annan', 'Thabo Mbeki', 2),
  Q('History', 'Gandhi led a peaceful independence movement in which country?', 'India', 'Pakistan', 'Egypt', 'Kenya', 2),
  Q('History', 'Who painted the ceiling of the Sistine Chapel?', 'Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Titian', 2),
  Q('History', 'Who painted The Starry Night?', 'Vincent van Gogh', 'Claude Monet', 'Paul Cézanne', 'Salvador Dalí', 2),
  Q('History', 'Which Paris fortress was stormed in 1789?', 'The Bastille', 'The Louvre', 'Versailles', 'Notre-Dame', 3),

  // ---------------- FOOD ----------------
  Q('Food', 'Sushi originally comes from which country?', 'Japan', 'China', 'Thailand', 'Korea', 1),
  Q('Food', 'What is the main ingredient in guacamole?', 'Avocado', 'Cucumber', 'Green pepper', 'Peas', 1),
  Q('Food', 'Which fruit wears its seeds on the outside?', 'Strawberry', 'Kiwi', 'Blueberry', 'Fig', 2),
  Q('Food', 'Pizza originated in which country?', 'Italy', 'Greece', 'France', 'USA', 1),
  Q('Food', 'What do bees produce that people eat?', 'Honey', 'Syrup', 'Nectar jam', 'Sugar', 1),
  Q('Food', 'Pickles are usually made from which vegetable?', 'Cucumbers', 'Zucchini', 'Celery', 'Green beans', 1),
  Q('Food', 'Which country is famous for the croissant?', 'France', 'Belgium', 'Switzerland', 'Denmark', 1),
  Q('Food', 'What is tofu made from?', 'Soybeans', 'Rice', 'Wheat', 'Potatoes', 2),
  Q('Food', 'Raisins are dried what?', 'Grapes', 'Plums', 'Cherries', 'Cranberries', 1),
  Q('Food', 'Traditional pesto contains which nut?', 'Pine nuts', 'Peanuts', 'Almonds', 'Cashews', 3),
  Q('Food', 'What is the main ingredient of hummus?', 'Chickpeas', 'Lentils', 'White beans', 'Eggplant', 2),
  Q('Food', 'Which cheese tops a classic pizza Margherita?', 'Mozzarella', 'Cheddar', 'Parmesan', 'Feta', 2),
  Q('Food', 'Chocolate is made from which bean?', 'Cacao beans', 'Coffee beans', 'Vanilla beans', 'Soy beans', 1),
  Q('Food', 'Paella is a famous dish from which country?', 'Spain', 'Portugal', 'Mexico', 'Italy', 2),
  Q('Food', 'Which fruit is dried to make prunes?', 'Plums', 'Apricots', 'Dates', 'Figs', 2),
  Q('Food', 'What is the main ingredient in bread?', 'Flour', 'Sugar', 'Butter', 'Milk', 1),
  Q('Food', 'What are french fries made from?', 'Potatoes', 'Corn', 'Rice', 'Parsnips', 1),
  Q('Food', 'Ketchup is mainly made from what?', 'Tomatoes', 'Red peppers', 'Beets', 'Plums', 1),
  Q('Food', 'Spaghetti and lasagna come from which country?', 'Italy', 'Greece', 'Spain', 'France', 1),
  Q('Food', 'What is sauerkraut made of?', 'Cabbage', 'Lettuce', 'Spinach', 'Kale', 2),
  Q('Food', 'Which country is famous for tacos?', 'Mexico', 'Spain', 'Brazil', 'Cuba', 1),
  Q('Food', 'Which country is famous for curry and naan bread?', 'India', 'China', 'Japan', 'Turkey', 1),
  Q('Food', 'What is the main ingredient in an omelet?', 'Eggs', 'Flour', 'Cheese', 'Milk', 1),
  Q('Food', 'Popcorn is made from which grain?', 'Corn', 'Wheat', 'Rice', 'Barley', 1),
  Q('Food', 'Oatmeal is made from which grain?', 'Oats', 'Wheat', 'Rye', 'Corn', 1),
  Q('Food', 'Which grain is sushi rolled with?', 'Rice', 'Quinoa', 'Couscous', 'Barley', 1),
  Q('Food', 'What green spicy paste is served with sushi?', 'Wasabi', 'Pesto', 'Guacamole', 'Mint sauce', 2),
  Q('Food', 'Which fruit is said to keep the doctor away?', 'Apple', 'Orange', 'Banana', 'Pear', 1),
  Q('Food', 'Which citrus fruit is yellow and sour?', 'Lemon', 'Orange', 'Grapefruit', 'Mandarin', 1),
  Q('Food', 'Which vegetable can make you cry when you cut it?', 'Onion', 'Carrot', 'Potato', 'Pepper', 1),
  Q('Food', 'Which orange vegetable is linked to good eyesight?', 'Carrot', 'Pumpkin', 'Sweet potato', 'Squash', 1),
  Q('Food', 'Broccoli looks like tiny green what?', 'Trees', 'Clouds', 'Hills', 'Flowers', 1),
  Q('Food', 'Which big green fruit has red flesh and black seeds?', 'Watermelon', 'Honeydew', 'Cantaloupe', 'Papaya', 1),
  Q('Food', 'Which fruit is fuzzy and brown outside but green inside?', 'Kiwi', 'Mango', 'Peach', 'Passion fruit', 1),
  Q('Food', 'Which tropical fruit has spiky skin and a leafy crown?', 'Pineapple', 'Coconut', 'Durian', 'Dragon fruit', 1),
  Q('Food', 'What do you get when you churn cream?', 'Butter', 'Cheese', 'Yogurt', 'Custard', 2),
  Q('Food', 'What is yogurt made from?', 'Milk', 'Eggs', 'Soy only', 'Coconut only', 1),
  Q('Food', 'Which cheese full of holes is linked with Switzerland?', 'Swiss cheese', 'Brie', 'Gouda', 'Blue cheese', 1),
  Q('Food', 'Which Italian dessert’s name means “pick me up”?', 'Tiramisu', 'Gelato', 'Cannoli', 'Panna cotta', 3),
  Q('Food', 'Which thin French pancake is often filled with sweet fillings?', 'A crêpe', 'A waffle', 'A scone', 'A blini', 2),
  Q('Food', 'Which breakfast food is cooked in an iron with a grid pattern?', 'Waffles', 'Pancakes', 'Toast', 'Muffins', 1),
  Q('Food', 'Maple syrup is made from what?', 'Tree sap', 'Honey', 'Sugar cane', 'Corn starch', 2),
  Q('Food', 'Which nut is used to make marzipan?', 'Almonds', 'Walnuts', 'Pecans', 'Pistachios', 3),
  Q('Food', 'Which nut flavor is Nutella known for?', 'Hazelnut', 'Peanut', 'Almond', 'Cashew', 2),
  Q('Food', 'Peanut butter and what make a classic sandwich?', 'Jelly', 'Honey', 'Cream cheese', 'Marshmallow', 1),
  Q('Food', 'What is the liquid inside a young coconut called?', 'Coconut water', 'Coconut oil', 'Coconut cream', 'Coconut juice-milk', 1),
  Q('Food', 'Which drink is made from fermented grapes?', 'Wine', 'Beer', 'Cider', 'Mead', 1),
  Q('Food', 'Which hot drink is brewed from roasted beans?', 'Coffee', 'Tea', 'Cocoa water', 'Chai only', 1),
  Q('Food', 'Which hot drink is brewed from dried leaves?', 'Tea', 'Coffee', 'Hot cider', 'Malt', 1),
  Q('Food', 'Which Mexican dish is a tortilla folded around melted cheese?', 'A quesadilla', 'A burrito', 'A tamale', 'An enchilada', 2),
  Q('Food', 'What Japanese soup is made with fermented soybean paste?', 'Miso soup', 'Ramen broth', 'Udon soup', 'Dashi jelly', 3),
  Q('Food', 'Which ring-shaped bread roll is boiled before baking?', 'A bagel', 'A pretzel', 'A donut', 'A croissant', 2),
  Q('Food', 'What is frozen sweetened cream called?', 'Ice cream', 'Sorbet', 'Slush', 'Frozen custard only', 1),
  Q('Food', 'Which green herb is the base of pesto?', 'Basil', 'Mint', 'Parsley', 'Cilantro', 2),
  Q('Food', 'Which red spice is made from ground sweet peppers?', 'Paprika', 'Saffron', 'Cayenne only', 'Sumac', 3),
  Q('Food', 'Which sweet spice comes from tree bark?', 'Cinnamon', 'Nutmeg', 'Clove', 'Ginger', 2),
  Q('Food', 'Which yellow spice gives curry its color?', 'Turmeric', 'Saffron', 'Mustard', 'Cumin', 3),

  // ---------------- SPORTS ----------------
  Q('Sports', 'How many players are on a soccer team on the field?', 'Eleven', 'Nine', 'Ten', 'Twelve', 1),
  Q('Sports', 'How often are the Summer Olympic Games held?', 'Every 4 years', 'Every 2 years', 'Every 5 years', 'Every year', 1),
  Q('Sports', 'In which sport do you score a touchdown?', 'American football', 'Rugby', 'Basketball', 'Cricket', 1),
  Q('Sports', 'How many rings are on the Olympic flag?', 'Five', 'Four', 'Six', 'Seven', 1),
  Q('Sports', 'Which sport is played with a shuttlecock?', 'Badminton', 'Tennis', 'Squash', 'Table tennis', 2),
  Q('Sports', 'How high is a basketball hoop?', '10 feet', '8 feet', '12 feet', '15 feet', 2),
  Q('Sports', 'In which sport can you hit a hole-in-one?', 'Golf', 'Cricket', 'Baseball', 'Polo', 1),
  Q('Sports', 'In tennis, what is a score of zero called?', 'Love', 'Nil', 'Duck', 'Blank', 2),
  Q('Sports', 'Wimbledon is a famous tournament in which sport?', 'Tennis', 'Golf', 'Cricket', 'Rowing', 1),
  Q('Sports', 'How many players per basketball team are on the court?', 'Five', 'Six', 'Seven', 'Four', 1),
  Q('Sports', 'In baseball, how many strikes make an out?', 'Three', 'Two', 'Four', 'Five', 1),
  Q('Sports', 'Which sport is played with a puck?', 'Ice hockey', 'Lacrosse', 'Field hockey', 'Curling', 1),
  Q('Sports', 'A marathon is about how many kilometers?', '42 km', '26 km', '50 km', '35 km', 2),
  Q('Sports', 'Which martial art comes from Japan?', 'Judo', 'Taekwondo', 'Kung fu', 'Muay Thai', 2),
  Q('Sports', 'How many points is a touchdown worth (before the extra point)?', '6', '7', '3', '5', 2),
  Q('Sports', 'How many points is a basketball free throw worth?', '1', '2', '3', '4', 1),
  Q('Sports', 'How many points is a basketball shot from beyond the arc?', '3', '2', '4', '5', 1),
  Q('Sports', 'In soccer, which player may use their hands in the penalty box?', 'The goalkeeper', 'The captain', 'The striker', 'Any defender', 1),
  Q('Sports', 'What color card sends a soccer player off the field?', 'Red', 'Yellow', 'Black', 'Blue', 1),
  Q('Sports', 'What color card is a warning in soccer?', 'Yellow', 'Red', 'Green', 'White', 1),
  Q('Sports', 'How many minutes long is a regulation soccer match?', '90', '60', '80', '100', 2),
  Q('Sports', 'How many periods are played in ice hockey?', 'Three', 'Two', 'Four', 'Five', 2),
  Q('Sports', 'How many quarters are in an NBA basketball game?', 'Four', 'Two', 'Three', 'Five', 1),
  Q('Sports', 'In golf, what is one stroke under par called?', 'A birdie', 'A bogey', 'An eagle', 'An albatross', 2),
  Q('Sports', 'In golf, what is one stroke over par called?', 'A bogey', 'A birdie', 'A slice', 'A dropshot', 2),
  Q('Sports', 'In golf, what is two strokes under par called?', 'An eagle', 'A birdie', 'A condor', 'A hawk', 3),
  Q('Sports', 'What do you knock down in bowling?', 'Pins', 'Wickets', 'Blocks', 'Cones', 1),
  Q('Sports', 'How many pins are in ten-pin bowling?', 'Ten', 'Nine', 'Twelve', 'Eight', 1),
  Q('Sports', 'What is a perfect score in ten-pin bowling?', '300', '200', '250', '500', 3),
  Q('Sports', 'Which racket sport is played against a wall?', 'Squash', 'Badminton', 'Tennis', 'Pickleball', 2),
  Q('Sports', 'What is table tennis also called?', 'Ping pong', 'Paddle smash', 'Mini tennis', 'Net ball', 1),
  Q('Sports', 'In tennis, what is the score called when both players have 40?', 'Deuce', 'Even', 'Level', 'Match point', 2),
  Q('Sports', 'Which sport has positions called pitcher and catcher?', 'Baseball', 'Cricket', 'Softball only', 'Lacrosse', 1),
  Q('Sports', 'Which sport has wickets and overs?', 'Cricket', 'Croquet', 'Rounders', 'Polo', 2),
  Q('Sports', 'Which country invented cricket?', 'England', 'Australia', 'India', 'South Africa', 2),
  Q('Sports', 'In which sport do you ride waves on a board?', 'Surfing', 'Rowing', 'Sailing', 'Kayaking', 1),
  Q('Sports', 'Which sport uses a pommel horse?', 'Gymnastics', 'Equestrian', 'Wrestling', 'Fencing', 2),
  Q('Sports', 'Which winter sport combines skiing and rifle shooting?', 'Biathlon', 'Nordic combined', 'Slalom', 'Skeleton', 3),
  Q('Sports', 'Which winter sport uses stones and brooms on ice?', 'Curling', 'Ice dancing', 'Luge', 'Bandy', 1),
  Q('Sports', 'Which sport is nicknamed “the sweet science”?', 'Boxing', 'Chess boxing', 'Fencing', 'Wrestling', 3),
  Q('Sports', 'In boxing, what does KO stand for?', 'Knockout', 'Kickoff', 'Knock over', 'Keep out', 1),
  Q('Sports', 'Which famous cycling race awards a yellow jersey?', 'The Tour de France', 'The Giro', 'The Vuelta', 'The Olympics', 2),
  Q('Sports', 'Which swimming stroke is named after an insect?', 'Butterfly', 'Dragonfly', 'Beetle', 'Mantis', 1),
  Q('Sports', 'In which sport do you spike a ball over a high net?', 'Volleyball', 'Tennis', 'Badminton', 'Handball', 1),
  Q('Sports', 'How many players per volleyball team are on court?', 'Six', 'Five', 'Seven', 'Eight', 2),
  Q('Sports', 'Which sport is played on horseback with mallets?', 'Polo', 'Cricket', 'Croquet', 'Jousting only', 2),
  Q('Sports', 'Which position throws the passes in American football?', 'Quarterback', 'Linebacker', 'Wide receiver', 'Center', 1),
  Q('Sports', 'What does NBA stand for?', 'National Basketball Association', 'North Basketball Alliance', 'National Ball Academy', 'New Basketball Association', 1),
  Q('Sports', 'Which trophy do NHL champions lift?', 'The Stanley Cup', 'The Grey Cup', 'The Ryder Cup', 'The Ashes', 2),
  Q('Sports', 'In which sport is the Ballon d’Or awarded?', 'Soccer', 'Tennis', 'Golf', 'Boxing', 2),
  Q('Sports', 'Usain Bolt set world records in which sport?', 'Sprinting', 'Swimming', 'Long jump', 'Cycling', 1),
  Q('Sports', 'Which sport features twisting dives from a springboard?', 'Diving', 'Gymnastics', 'Trampolining', 'Synchro swim', 1),
  Q('Sports', 'What is scoring three goals in one game called?', 'A hat-trick', 'A triple', 'A trifecta', 'A turkey', 1),
  Q('Sports', 'Which of these is NOT an Olympic ring color?', 'Purple', 'Red', 'Green', 'Black', 2),
  Q('Sports', 'In karate, which belt color usually marks the highest rank?', 'Black', 'Red', 'White', 'Brown', 1),
  Q('Sports', 'A dojo is a training hall for what?', 'Martial arts', 'Rowing', 'Gymnastics', 'Weightlifting', 2),
  Q('Sports', 'How many holes are in a full round of golf?', '18', '9', '12', '21', 1),
  Q('Sports', 'What surface is Wimbledon played on?', 'Grass', 'Clay', 'Hard court', 'Carpet', 2),
  Q('Sports', 'How many points usually win a volleyball set?', '25', '15', '21', '30', 3),

  // ---------------- SPACE ----------------
  Q('Space', 'Which planet is known as the Red Planet?', 'Mars', 'Venus', 'Jupiter', 'Mercury', 1),
  Q('Space', 'What is the largest planet in our solar system?', 'Jupiter', 'Saturn', 'Neptune', 'Earth', 1),
  Q('Space', 'Which planet is famous for its rings?', 'Saturn', 'Mars', 'Venus', 'Mercury', 1),
  Q('Space', 'Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Earth', 'Mars', 1),
  Q('Space', 'What is Earth’s natural satellite called?', 'The Moon', 'Titan', 'Europa', 'Phobos', 1),
  Q('Space', 'How many planets are in our solar system?', 'Eight', 'Nine', 'Seven', 'Ten', 1),
  Q('Space', 'Who was the first person to walk on the Moon?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn', 1),
  Q('Space', 'The Sun is a what?', 'A star', 'A planet', 'A comet', 'A galaxy', 1),
  Q('Space', 'What galaxy do we live in?', 'The Milky Way', 'Andromeda', 'The Whirlpool', 'The Sombrero', 1),
  Q('Space', 'Which planet has the Great Red Spot?', 'Jupiter', 'Mars', 'Saturn', 'Neptune', 2),
  Q('Space', 'What is the hottest planet in our solar system?', 'Venus', 'Mercury', 'Mars', 'Jupiter', 3),
  Q('Space', 'A space rock burning up in the atmosphere is called a what?', 'Meteor', 'Comet', 'Asteroid', 'Nebula', 2),
  Q('Space', 'Which famous space telescope launched in 1990?', 'Hubble', 'Kepler', 'Galileo', 'Voyager', 2),
  Q('Space', 'What do astronauts wear in space to survive?', 'Spacesuits', 'Wetsuits', 'Flight jackets', 'Parachutes', 1),
  Q('Space', 'Which planet is the smallest in our solar system?', 'Mercury', 'Mars', 'Pluto', 'Venus', 2),
  Q('Space', 'Which planet spins on its side?', 'Uranus', 'Neptune', 'Saturn', 'Venus', 3),
  Q('Space', 'Which planet is farthest from the Sun?', 'Neptune', 'Uranus', 'Saturn', 'Pluto', 2),
  Q('Space', 'Which planet is often called Earth’s twin?', 'Venus', 'Mars', 'Mercury', 'Neptune', 3),
  Q('Space', 'Which dwarf planet used to be counted as the ninth planet?', 'Pluto', 'Ceres', 'Eris', 'Makemake', 1),
  Q('Space', 'What is a group of stars forming a pattern called?', 'A constellation', 'A cluster', 'A nebula', 'A galaxy', 1),
  Q('Space', 'The Big Dipper is part of which constellation?', 'Ursa Major', 'Orion', 'Cassiopeia', 'Leo', 3),
  Q('Space', 'What is the North Star called?', 'Polaris', 'Sirius', 'Vega', 'Rigel', 2),
  Q('Space', 'What is an exploding star called?', 'A supernova', 'A quasar', 'A pulsar', 'A flare', 2),
  Q('Space', 'What region of space has gravity so strong light cannot escape?', 'A black hole', 'A wormhole', 'A dark nebula', 'A void', 1),
  Q('Space', 'What is the Sun mostly made of?', 'Hydrogen', 'Oxygen', 'Carbon', 'Iron', 2),
  Q('Space', 'How long does Earth take to orbit the Sun?', 'One year', 'One month', 'One day', 'Ten years', 1),
  Q('Space', 'About how long does the Moon take to orbit Earth?', 'One month', 'One day', 'One year', 'One week', 2),
  Q('Space', 'What mainly causes ocean tides?', 'The Moon’s gravity', 'The wind', 'Earth’s spin only', 'Underwater volcanoes', 2),
  Q('Space', 'What icy space object grows a glowing tail near the Sun?', 'A comet', 'An asteroid', 'A meteorite', 'A moonlet', 1),
  Q('Space', 'Which famous comet returns about every 76 years?', 'Halley’s Comet', 'Hale-Bopp', 'Encke', 'Swift-Tuttle', 3),
  Q('Space', 'Where is the main asteroid belt?', 'Between Mars and Jupiter', 'Between Earth and Mars', 'Past Neptune', 'Inside Mercury’s orbit', 3),
  Q('Space', 'What kind of animal was Laika, the first orbital space traveler?', 'A dog', 'A cat', 'A monkey', 'A mouse', 2),
  Q('Space', 'What was the name of the first Moon landing mission?', 'Apollo 11', 'Apollo 13', 'Gemini 4', 'Mercury 7', 2),
  Q('Space', 'Who was the second person to walk on the Moon?', 'Buzz Aldrin', 'Michael Collins', 'Alan Shepard', 'Pete Conrad', 3),
  Q('Space', 'Which US agency runs American space missions?', 'NASA', 'NORAD', 'NOAA', 'FAA', 1),
  Q('Space', 'What is the Russian word for an astronaut?', 'Cosmonaut', 'Spacenaut', 'Astronik', 'Stellanaut', 2),
  Q('Space', 'What does ISS stand for?', 'International Space Station', 'Interstellar Space Ship', 'Inner Solar System', 'International Star Survey', 1),
  Q('Space', 'Olympus Mons, the tallest volcano known, is on which planet?', 'Mars', 'Venus', 'Earth', 'Mercury', 3),
  Q('Space', 'What are Saturn’s rings mostly made of?', 'Ice and rock', 'Gas', 'Dust only', 'Metal', 2),
  Q('Space', 'What do we call the Moon phase when it is fully lit?', 'Full moon', 'New moon', 'Half moon', 'Crescent', 1),
  Q('Space', 'What do we call the Moon phase when it is completely dark?', 'New moon', 'Full moon', 'Eclipse moon', 'Gibbous', 2),
  Q('Space', 'What blocks the Sun during a solar eclipse?', 'The Moon', 'Earth’s shadow', 'Venus', 'Clouds', 1),
  Q('Space', 'What is the path a planet takes around the Sun called?', 'An orbit', 'A circuit', 'A track', 'A revolution lane', 1),
  Q('Space', 'What is the closest large galaxy to the Milky Way?', 'Andromeda', 'Triangulum', 'The Magellanic Cloud', 'Centaurus A', 3),
  Q('Space', 'What layer protects Earth from small meteors and radiation?', 'The atmosphere', 'The ozone hole', 'The crust', 'The magnetopause only', 2),

  // ---------------- MOVIES & TV ----------------
  Q('Movies & TV', 'Buzz Lightyear appears in which movie series?', 'Toy Story', 'Shrek', 'Cars', 'Monsters, Inc.', 1),
  Q('Movies & TV', 'What is the wizard school in Harry Potter called?', 'Hogwarts', 'Narnia', 'Rivendell', 'Camelot', 1),
  Q('Movies & TV', 'In The Lion King, what animal is Simba?', 'A lion', 'A tiger', 'A leopard', 'A hyena', 1),
  Q('Movies & TV', 'What is the name of Mickey Mouse’s dog?', 'Pluto', 'Goofy', 'Rex', 'Max', 1),
  Q('Movies & TV', 'In Finding Nemo, what kind of fish is Nemo?', 'A clownfish', 'A goldfish', 'An angelfish', 'A pufferfish', 1),
  Q('Movies & TV', 'What kind of creature is Shrek?', 'An ogre', 'A troll', 'A giant', 'A goblin', 1),
  Q('Movies & TV', 'Which superhero comes from the planet Krypton?', 'Superman', 'Batman', 'Thor', 'Green Lantern', 1),
  Q('Movies & TV', 'Elsa sings “Let It Go” in which movie?', 'Frozen', 'Moana', 'Tangled', 'Brave', 1),
  Q('Movies & TV', 'The Minions appear in which movie series?', 'Despicable Me', 'Madagascar', 'Ice Age', 'Trolls', 1),
  Q('Movies & TV', 'Darth Vader is a villain in which saga?', 'Star Wars', 'Star Trek', 'Dune', 'The Matrix', 1),
  Q('Movies & TV', 'Which movie features a time-traveling DeLorean?', 'Back to the Future', 'The Terminator', 'Looper', 'Interstellar', 2),
  Q('Movies & TV', 'SpongeBob SquarePants lives in what?', 'A pineapple', 'A shell', 'A shipwreck', 'A cave', 1),
  Q('Movies & TV', 'Batman protects which city?', 'Gotham City', 'Metropolis', 'Star City', 'Central City', 1),
  Q('Movies & TV', 'In The Lord of the Rings, hobbits live in the what?', 'The Shire', 'Mordor', 'Gondor', 'The Misty Mountains', 2),
  Q('Movies & TV', 'Which movie features a frog named Kermit?', 'The Muppet Movie', 'Ratatouille', 'Zootopia', 'Rio', 2),
  Q('Movies & TV', 'What kind of animal is Dumbo?', 'An elephant', 'A donkey', 'A hippo', 'A rhino', 1),
  Q('Movies & TV', 'What kind of animal is Bambi?', 'A deer', 'A rabbit', 'A moose', 'An elk', 1),
  Q('Movies & TV', 'Which Pixar movie takes place inside a girl’s mind?', 'Inside Out', 'Soul', 'Coco', 'Luca', 2),
  Q('Movies & TV', 'Which Pixar movie stars a rat who loves to cook?', 'Ratatouille', 'A Bug’s Life', 'Cars', 'Up', 1),
  Q('Movies & TV', 'Which Pixar movie stars a lonely trash-collecting robot?', 'WALL-E', 'Big Hero 6', 'Robots', 'The Iron Giant', 1),
  Q('Movies & TV', 'Which Pixar movie is about monsters who scare kids for power?', 'Monsters, Inc.', 'Hotel Transylvania', 'Coraline', 'ParaNorman', 1),
  Q('Movies & TV', 'Lightning McQueen races in which movie?', 'Cars', 'Turbo', 'Wreck-It Ralph', 'Hot Wheels', 1),
  Q('Movies & TV', 'In Up, what lifts the house into the sky?', 'Balloons', 'A tornado', 'Rockets', 'A giant bird', 1),
  Q('Movies & TV', 'Ariel is the star of which Disney movie?', 'The Little Mermaid', 'Moana', 'Pocahontas', 'Mulan', 1),
  Q('Movies & TV', 'Which Disney princess has magical seventy-foot hair?', 'Rapunzel', 'Aurora', 'Belle', 'Cinderella', 1),
  Q('Movies & TV', 'Who pops out of the lamp in Aladdin?', 'The Genie', 'Abu', 'Jafar', 'Iago', 1),
  Q('Movies & TV', 'In Moana, which demigod sails with her?', 'Maui', 'Tamatoa', 'Tui', 'Kai', 2),
  Q('Movies & TV', 'What is the snowman’s name in Frozen?', 'Olaf', 'Sven', 'Kristoff', 'Hans', 1),
  Q('Movies & TV', 'Who is Elsa’s sister?', 'Anna', 'Ariel', 'Elena', 'Aurora', 1),
  Q('Movies & TV', 'Baloo the bear appears in which movie?', 'The Jungle Book', 'Brother Bear', 'Open Season', 'Paddington', 2),
  Q('Movies & TV', 'Whose wooden nose grows when he lies?', 'Pinocchio', 'Geppetto', 'Peter Pan', 'Dopey', 1),
  Q('Movies & TV', 'How many Dalmatians are in the famous Disney title?', '101', '99', '100', '102', 1),
  Q('Movies & TV', 'Katniss Everdeen stars in which series?', 'The Hunger Games', 'Divergent', 'The Maze Runner', 'Twilight', 2),
  Q('Movies & TV', 'What position does Harry Potter play in Quidditch?', 'Seeker', 'Keeper', 'Chaser', 'Beater', 2),
  Q('Movies & TV', 'What is Harry Potter’s owl called?', 'Hedwig', 'Errol', 'Crookshanks', 'Fawkes', 2),
  Q('Movies & TV', 'Which house is Harry Potter sorted into?', 'Gryffindor', 'Slytherin', 'Hufflepuff', 'Ravenclaw', 1),
  Q('Movies & TV', 'Who is the dark wizard villain of Harry Potter?', 'Voldemort', 'Grindelwald', 'Snape', 'Lucius', 1),
  Q('Movies & TV', 'Who is the grey wizard in The Lord of the Rings?', 'Gandalf', 'Saruman', 'Radagast', 'Elrond', 1),
  Q('Movies & TV', 'Which creature calls the Ring “my precious”?', 'Gollum', 'An orc', 'A troll', 'Smaug', 1),
  Q('Movies & TV', 'What is the name of Han Solo’s ship?', 'The Millennium Falcon', 'The Star Destroyer', 'The X-Wing', 'The Enterprise', 2),
  Q('Movies & TV', 'What furry species is Chewbacca?', 'A Wookiee', 'An Ewok', 'A Gungan', 'A Hutt', 2),
  Q('Movies & TV', 'Which small green Jedi master trains Luke?', 'Yoda', 'Obi-Wan', 'Mace Windu', 'Qui-Gon', 1),
  Q('Movies & TV', 'Which Marvel hero turns big and green when angry?', 'The Hulk', 'Thor', 'Groot', 'Vision', 1),
  Q('Movies & TV', 'Which Marvel hero wields the hammer Mjolnir?', 'Thor', 'Loki', 'Odin', 'Hawkeye', 1),
  Q('Movies & TV', 'Which Marvel hero flies in a red and gold metal suit?', 'Iron Man', 'War Machine', 'Falcon', 'Vision', 1),
  Q('Movies & TV', 'Which hero climbs walls and shoots webs?', 'Spider-Man', 'Ant-Man', 'Daredevil', 'Black Panther', 1),
  Q('Movies & TV', 'Which hero throws a shield with a white star?', 'Captain America', 'Captain Marvel', 'Hawkeye', 'Bucky', 1),
  Q('Movies & TV', 'What is the name of Batman’s butler?', 'Alfred', 'Jarvis', 'Lucius', 'Gordon', 2),
  Q('Movies & TV', 'Who is Batman’s classic sidekick?', 'Robin', 'Nightwing only', 'Batgirl', 'Azrael', 1),
  Q('Movies & TV', 'Which movie features a giant great white shark?', 'Jaws', 'The Meg', 'Deep Blue Sea', 'Sharknado', 1),
  Q('Movies & TV', 'Which movie brings dinosaurs back in a theme park?', 'Jurassic Park', 'King Kong', 'Godzilla', 'The Lost World only', 1),
  Q('Movies & TV', 'Which movie features a friendly alien who phones home?', 'E.T.', 'Lilo & Stitch', 'Arrival', 'Paul', 1),
  Q('Movies & TV', 'In which holiday movie does Kevin defend his house alone?', 'Home Alone', 'Elf', 'Jingle All the Way', 'The Santa Clause', 1),
  Q('Movies & TV', 'What is the name of the Grinch’s dog?', 'Max', 'Rex', 'Buddy', 'Sam', 3),
  Q('Movies & TV', 'Buddy the Elf stars in which movie?', 'Elf', 'The Polar Express', 'Noelle', 'Klaus', 1),
  Q('Movies & TV', 'Which cartoon family lives in Springfield?', 'The Simpsons', 'The Griffins', 'The Flintstones', 'The Jetsons', 1),
  Q('Movies & TV', 'What color are the Simpsons?', 'Yellow', 'Orange', 'Pink', 'Tan', 1),
  Q('Movies & TV', 'In Tom and Jerry, what animal is Jerry?', 'A mouse', 'A cat', 'A rat', 'A hamster', 1),
  Q('Movies & TV', 'What breed-defying animal is Scooby-Doo?', 'A dog', 'A wolf', 'A bear', 'A hyena', 1),
  Q('Movies & TV', 'What is Peppa Pig’s little brother called?', 'George', 'Jack', 'Henry', 'Oliver', 2),
  Q('Movies & TV', 'Who is SpongeBob’s starfish best friend?', 'Patrick', 'Squidward', 'Larry', 'Plankton', 1),
  Q('Movies & TV', 'What kind of fish is Dory?', 'A blue tang', 'A clownfish', 'A guppy', 'A betta', 3),

  // ---------------- MUSIC ----------------
  Q('Music', 'How many strings does a standard guitar have?', 'Six', 'Four', 'Five', 'Seven', 1),
  Q('Music', 'Beethoven was famous as a what?', 'Composer', 'Painter', 'Sculptor', 'Poet', 1),
  Q('Music', 'Which instrument has 88 keys?', 'Piano', 'Organ', 'Accordion', 'Harpsichord', 2),
  Q('Music', 'The Beatles came from which city?', 'Liverpool', 'London', 'Manchester', 'Dublin', 2),
  Q('Music', 'A violin is played with a what?', 'Bow', 'Pick', 'Mallet', 'Reed', 1),
  Q('Music', 'Which of these is a brass instrument?', 'Trumpet', 'Clarinet', 'Violin', 'Flute', 2),
  Q('Music', 'Which drum in a drum kit is played with a foot pedal?', 'Bass drum', 'Snare drum', 'Tom-tom', 'Bongo', 2),
  Q('Music', 'In the do-re-mi scale, what comes after “do”?', 'Re', 'Mi', 'Fa', 'La', 1),
  Q('Music', 'A DJ traditionally spins records on a what?', 'Turntable', 'Keyboard', 'Drum machine', 'Jukebox', 1),
  Q('Music', 'What was Mozart’s first name?', 'Wolfgang', 'Ludwig', 'Johann', 'Franz', 3),
  Q('Music', 'Which guitar-family instrument plays the lowest notes?', 'Bass guitar', 'Ukulele', 'Banjo', 'Mandolin', 1),
  Q('Music', 'Which small four-string instrument comes from Hawaii?', 'Ukulele', 'Banjo', 'Fiddle', 'Lute', 1),
  Q('Music', 'Violins and cellos belong to which orchestra section?', 'Strings', 'Brass', 'Woodwinds', 'Percussion', 1),
  Q('Music', 'Flutes and clarinets belong to which orchestra section?', 'Woodwinds', 'Strings', 'Brass', 'Percussion', 2),
  Q('Music', 'What is the largest string instrument in an orchestra?', 'Double bass', 'Cello', 'Harp', 'Viola', 2),
  Q('Music', 'Who leads an orchestra with a baton?', 'The conductor', 'The composer', 'The first violin', 'The manager', 1),
  Q('Music', 'What are the five lines that music is written on called?', 'A staff', 'A scale', 'A ledger', 'A bar', 2),
  Q('Music', 'What symbol at the start of a staff sets the pitch range?', 'A clef', 'A note', 'A rest', 'A sharp', 2),
  Q('Music', 'What do you call several notes played together?', 'A chord', 'A scale', 'A riff', 'A beat', 1),
  Q('Music', 'How many notes are in an octave, counting both ends?', 'Eight', 'Six', 'Seven', 'Ten', 2),
  Q('Music', 'What does “forte” mean in music?', 'Loud', 'Soft', 'Fast', 'Slow', 2),
  Q('Music', 'What does “piano” mean as a musical instruction?', 'Soft', 'Loud', 'Quick', 'Sad', 2),
  Q('Music', 'What is the speed of a piece of music called?', 'Tempo', 'Rhythm', 'Pitch', 'Volume', 1),
  Q('Music', 'Which composer wrote Für Elise?', 'Beethoven', 'Bach', 'Chopin', 'Brahms', 2),
  Q('Music', 'Which composer wrote The Four Seasons?', 'Vivaldi', 'Handel', 'Haydn', 'Verdi', 3),
  Q('Music', 'Which “King of Rock and Roll” sang Hound Dog?', 'Elvis Presley', 'Chuck Berry', 'Buddy Holly', 'Johnny Cash', 1),
  Q('Music', 'Which band recorded Hey Jude?', 'The Beatles', 'The Rolling Stones', 'The Beach Boys', 'Queen', 2),
  Q('Music', 'Which pop star recorded Thriller?', 'Michael Jackson', 'Prince', 'Stevie Wonder', 'Lionel Richie', 1),
  Q('Music', 'What is Michael Jackson’s famous backwards glide called?', 'The moonwalk', 'The slide', 'The glide-step', 'The backspin', 1),
  Q('Music', 'Which large instrument has 47 strings and pedals?', 'Harp', 'Grand piano', 'Cello', 'Zither', 3),
  Q('Music', 'Which percussion instruments are crashing metal plates?', 'Cymbals', 'Triangles', 'Gongs only', 'Chimes', 1),
  Q('Music', 'Which shaken instrument has beads inside?', 'Maracas', 'Castanets', 'Claves', 'Guiro', 1),
  Q('Music', 'Which Scottish instrument is played with a bag of air?', 'Bagpipes', 'Accordion', 'Concertina', 'Pan flute', 1),
  Q('Music', 'Which long wooden drone instrument comes from Australia?', 'Didgeridoo', 'Pan pipes', 'Ocarina', 'Alphorn', 2),
  Q('Music', 'What is a song sung to lull babies to sleep called?', 'A lullaby', 'A ballad', 'A hymn', 'A serenade', 1),
  Q('Music', 'What is singing without any instruments called?', 'A cappella', 'Solo', 'Unplugged', 'Acoustic', 2),
  Q('Music', 'What are the words of a song called?', 'Lyrics', 'Verses only', 'Scripts', 'Lines', 1),
  Q('Music', 'Which simple wind instrument do many kids learn first at school?', 'Recorder', 'Oboe', 'Piccolo', 'Harmonica', 1),
  Q('Music', 'Which brass instrument changes notes with a slide?', 'Trombone', 'Trumpet', 'Tuba', 'French horn', 2),
  Q('Music', 'What is a group of four musicians called?', 'A quartet', 'A trio', 'A quintet', 'A duet', 2),

  // ---------------- GAMES ----------------
  Q('Games', 'What is the name of Mario’s brother?', 'Luigi', 'Wario', 'Toad', 'Yoshi', 1),
  Q('Games', 'What type of Pokémon is Pikachu?', 'Electric', 'Fire', 'Water', 'Grass', 1),
  Q('Games', 'What does a Creeper do in Minecraft?', 'Explodes', 'Shoots arrows', 'Steals items', 'Builds walls', 1),
  Q('Games', 'Sonic is what kind of animal?', 'A hedgehog', 'A fox', 'A porcupine', 'A rabbit', 1),
  Q('Games', 'In Tetris, what do you stack?', 'Falling blocks', 'Marbles', 'Cards', 'Rings', 1),
  Q('Games', 'Link is the hero of which game series?', 'The Legend of Zelda', 'Final Fantasy', 'Metroid', 'Kirby', 2),
  Q('Games', 'What does Pac-Man eat as he moves through the maze?', 'Dots', 'Coins', 'Stars', 'Cherries only', 1),
  Q('Games', 'Which company makes the PlayStation?', 'Sony', 'Nintendo', 'Microsoft', 'Sega', 1),
  Q('Games', 'What color is Kirby?', 'Pink', 'Blue', 'Yellow', 'Green', 1),
  Q('Games', 'In chess, which piece moves in an L shape?', 'The knight', 'The bishop', 'The rook', 'The queen', 2),
  Q('Games', 'In Among Us, what do crewmates do to win?', 'Complete tasks', 'Collect coins', 'Build ships', 'Catch fish', 1),
  Q('Games', 'Donkey Kong famously throws what?', 'Barrels', 'Bananas', 'Hammers', 'Coconuts', 1),
  Q('Games', 'In which game series do you catch creatures with Poké Balls?', 'Pokémon', 'Digimon', 'Monster Hunter', 'Yo-kai Watch', 1),
  Q('Games', 'In Mario games, what do you collect for points and lives?', 'Coins', 'Gems', 'Rings', 'Orbs', 1),
  Q('Games', 'Frogger is a classic game about a frog doing what?', 'Crossing a busy road', 'Baking pies', 'Racing cars', 'Fighting robots', 1),
  Q('Games', 'Who is Mario’s dinosaur companion?', 'Yoshi', 'Birdo', 'Bowser Jr.', 'Kamek', 1),
  Q('Games', 'Who kidnaps Princess Peach?', 'Bowser', 'Wario', 'King Boo', 'Donkey Kong', 1),
  Q('Games', 'What does a Super Mushroom do to Mario?', 'Makes him bigger', 'Makes him fly', 'Gives fireballs', 'Makes him invisible', 1),
  Q('Games', 'What is Mario’s original job?', 'Plumber', 'Carpenter only', 'Chef', 'Doctor', 1),
  Q('Games', 'Which fire-type starter evolves into Charizard?', 'Charmander', 'Torchic', 'Cyndaquil', 'Fennekin', 2),
  Q('Games', 'Who is Pikachu’s trainer in the animated series?', 'Ash', 'Brock', 'Gary', 'Misty', 1),
  Q('Games', 'What color is the top half of a standard Poké Ball?', 'Red', 'Blue', 'White', 'Yellow', 1),
  Q('Games', 'Which red ghost chases Pac-Man?', 'Blinky', 'Pinky', 'Inky', 'Clyde', 3),
  Q('Games', 'In Minecraft, what tool do you mine stone with?', 'A pickaxe', 'A shovel', 'An axe', 'A hoe', 1),
  Q('Games', 'In Minecraft, what do you use to craft items in a 3x3 grid?', 'A crafting table', 'A furnace', 'An anvil', 'A chest', 1),
  Q('Games', 'In Minecraft, what do you build to travel to the Nether?', 'A portal', 'A boat', 'A ladder', 'A rail line', 2),
  Q('Games', 'Steve and Alex are the default characters of which game?', 'Minecraft', 'Terraria', 'Roblox', 'Fortnite', 1),
  Q('Games', 'In Fortnite, what flying vehicle do you drop from?', 'The Battle Bus', 'A plane', 'A blimp', 'A helicopter', 2),
  Q('Games', 'What color is Sonic the Hedgehog?', 'Blue', 'Green', 'Red', 'Purple', 1),
  Q('Games', 'Who is Sonic’s two-tailed fox friend?', 'Tails', 'Knuckles', 'Shadow', 'Silver', 2),
  Q('Games', 'Who is Sonic’s red echidna rival?', 'Knuckles', 'Shadow', 'Eggman', 'Big', 2),
  Q('Games', 'Which company makes Mario games?', 'Nintendo', 'Sony', 'Sega', 'Capcom', 1),
  Q('Games', 'Which company makes the Xbox?', 'Microsoft', 'Sony', 'Nintendo', 'Valve', 1),
  Q('Games', 'Which handheld console made Tetris famous in 1989?', 'Game Boy', 'Game Gear', 'PSP', 'DS', 2),
  Q('Games', 'What does NPC stand for?', 'Non-player character', 'New player class', 'Neutral party control', 'No physical contact', 2),
  Q('Games', 'What do you call a spot where your progress is saved?', 'A save point', 'A base', 'A respawn den', 'A vault', 1),
  Q('Games', 'In chess, which piece can only move diagonally?', 'The bishop', 'The rook', 'The knight', 'The pawn', 2),
  Q('Games', 'In chess, which is the most powerful piece?', 'The queen', 'The king', 'The rook', 'The knight', 1),
  Q('Games', 'In chess, what is it called when the king cannot escape capture?', 'Checkmate', 'Stalemate', 'Check', 'En passant', 1),
  Q('Games', 'In checkers, what happens when a piece reaches the far row?', 'It gets kinged', 'It explodes', 'It is removed', 'It turns invisible', 1),
  Q('Games', 'How many squares are on a chessboard?', '64', '81', '100', '49', 2),
  Q('Games', 'In Monopoly, how much do you collect for passing GO?', '$200', '$100', '$500', '$50', 2),
  Q('Games', 'What is the most expensive property in classic US Monopoly?', 'Boardwalk', 'Park Place', 'Marvin Gardens', 'Pennsylvania Avenue', 3),
  Q('Games', 'Colonel Mustard appears in which board game?', 'Clue', 'Risk', 'Sorry!', 'Life', 2),
  Q('Games', 'Which word game uses letter tiles with point values?', 'Scrabble', 'Boggle', 'Hangman', 'Wordle', 1),
  Q('Games', 'Which two letters are worth 10 points in Scrabble?', 'Q and Z', 'X and J', 'K and V', 'W and Y', 3),
  Q('Games', 'In which card game do you shout when you have one card left?', 'Uno', 'Go Fish', 'Crazy Eights', 'Snap', 1),
  Q('Games', 'How many cards are in a standard deck without jokers?', '52', '48', '54', '50', 1),
  Q('Games', 'How many dots are on a standard six-sided die in total?', '21', '18', '24', '20', 3),
  Q('Games', 'Master Chief is the hero of which game series?', 'Halo', 'Doom', 'Destiny', 'Gears of War', 2),
  Q('Games', 'In which cozy game do you restore your grandfather’s farm?', 'Stardew Valley', 'Animal Crossing', 'Harvest Moon only', 'Minecraft', 3),
  Q('Games', 'Tom Nook runs the shop in which game series?', 'Animal Crossing', 'Stardew Valley', 'The Sims', 'Zelda', 2),
  Q('Games', 'Which puzzle game features portals and the AI GLaDOS?', 'Portal', 'Half-Life', 'The Talos Principle', 'Quake', 3),
  Q('Games', 'What does RPG stand for in gaming?', 'Role-playing game', 'Rapid player gun', 'Real player group', 'Random puzzle game', 2),
  Q('Games', 'What do you call the big enemy at the end of a game?', 'The final boss', 'The end knight', 'The last guard', 'The mega foe', 1),
  Q('Games', 'In Rock Paper Scissors, what beats rock?', 'Paper', 'Scissors', 'Nothing', 'Fire', 1),
  Q('Games', 'Which game is played on a 3x3 grid with X and O?', 'Tic-tac-toe', 'Connect Four', 'Checkers', 'Othello', 1),
  Q('Games', 'In which classic game do you sink your opponent’s fleet?', 'Battleship', 'Risk', 'Stratego', 'Sea Quest', 1),
  Q('Games', 'In which game do you drop discs to line up four in a row?', 'Connect Four', 'Othello', 'Checkers', 'Mancala', 1),
  Q('Games', 'Lara Croft stars in which adventure series?', 'Tomb Raider', 'Uncharted', 'Far Cry', 'Assassin’s Creed', 2),
  Q('Games', 'In Angry Birds, what do the birds attack?', 'Pigs', 'Wolves', 'Robots', 'Cats', 1),
  Q('Games', 'In which mobile game do you slice flying fruit?', 'Fruit Ninja', 'Candy Crush', 'Subway Surfers', 'Temple Run', 1),

  // ---------------- WORDS ----------------
  Q('Words', 'What is the opposite of “ancient”?', 'Modern', 'Old', 'Historic', 'Classic', 1),
  Q('Words', 'What is the plural of “mouse”?', 'Mice', 'Mouses', 'Meese', 'Mouse', 1),
  Q('Words', 'Which of these words is a palindrome?', 'Level', 'Ladder', 'Mirror', 'Turtle', 2),
  Q('Words', 'Which punctuation mark ends a question?', 'Question mark', 'Period', 'Comma', 'Colon', 1),
  Q('Words', 'Which word means the same as “happy”?', 'Joyful', 'Gloomy', 'Angry', 'Tired', 1),
  Q('Words', 'How many letters are in the English alphabet?', '26', '24', '25', '27', 1),
  Q('Words', 'Which language has the most native speakers worldwide?', 'Mandarin Chinese', 'English', 'Spanish', 'Hindi', 2),
  Q('Words', 'A person who writes books is called an what?', 'Author', 'Editor', 'Actor', 'Agent', 1),
  Q('Words', 'What is the opposite of “generous”?', 'Stingy', 'Kind', 'Wealthy', 'Careful', 2),
  Q('Words', 'Which of these words is a verb?', 'Jump', 'Blue', 'Quickly', 'Happiness', 1),
  Q('Words', '“Bonjour” means hello in which language?', 'French', 'Italian', 'Spanish', 'Portuguese', 1),
  Q('Words', 'Words that sound alike but mean different things are called what?', 'Homophones', 'Synonyms', 'Antonyms', 'Acronyms', 2),
  Q('Words', '“Hola” means hello in which language?', 'Spanish', 'French', 'German', 'Greek', 1),
  Q('Words', 'What is the dot over a lowercase “i” called?', 'A tittle', 'A jot', 'A speck', 'A serif', 3),
  Q('Words', 'What is the opposite of “hot”?', 'Cold', 'Warm', 'Cool only', 'Mild', 1),
  Q('Words', 'What is the opposite of “begin”?', 'End', 'Start', 'Continue', 'Pause', 1),
  Q('Words', 'What is the opposite of “victory”?', 'Defeat', 'Battle', 'Retreat', 'Draw', 1),
  Q('Words', 'What is the opposite of “brave”?', 'Cowardly', 'Strong', 'Careless', 'Quiet', 1),
  Q('Words', 'What is the opposite of “expand”?', 'Shrink', 'Grow', 'Stretch', 'Spread', 1),
  Q('Words', 'What is the plural of “child”?', 'Children', 'Childs', 'Childes', 'Childrens', 1),
  Q('Words', 'What is the plural of “goose”?', 'Geese', 'Gooses', 'Geeses', 'Goose', 1),
  Q('Words', 'What is the plural of “tooth”?', 'Teeth', 'Tooths', 'Toothes', 'Teeths', 1),
  Q('Words', 'What is the plural of “person”?', 'People', 'Persons only', 'Peoples only', 'Personses', 1),
  Q('Words', 'What is the plural of “cactus”?', 'Cacti', 'Cactuses only', 'Cactum', 'Cactus', 3),
  Q('Words', 'Which word is a synonym of “big”?', 'Enormous', 'Tiny', 'Narrow', 'Short', 1),
  Q('Words', 'Which word is a synonym of “fast”?', 'Rapid', 'Sluggish', 'Steady', 'Late', 1),
  Q('Words', 'Which word is a synonym of “smart”?', 'Clever', 'Slow', 'Loud', 'Lazy', 1),
  Q('Words', 'Which word is a synonym of “angry”?', 'Furious', 'Calm', 'Cheerful', 'Sleepy', 1),
  Q('Words', 'What is a word that imitates a sound called, like “buzz”?', 'Onomatopoeia', 'Alliteration', 'Assonance', 'Hyperbole', 3),
  Q('Words', 'A comparison using “like” or “as” is called a what?', 'Simile', 'Metaphor', 'Idiom', 'Allegory', 2),
  Q('Words', 'A direct comparison without “like” or “as” is called a what?', 'Metaphor', 'Simile', 'Proverb', 'Cliché', 2),
  Q('Words', 'Words with opposite meanings are called what?', 'Antonyms', 'Synonyms', 'Homonyms', 'Acronyms', 2),
  Q('Words', 'Words with the same meaning are called what?', 'Synonyms', 'Antonyms', 'Homophones', 'Palindromes', 2),
  Q('Words', 'What is the first letter of the Greek alphabet?', 'Alpha', 'Beta', 'Omega', 'Delta', 2),
  Q('Words', 'What is the last letter of the Greek alphabet?', 'Omega', 'Zeta', 'Sigma', 'Alpha', 2),
  Q('Words', '“Danke” means thank you in which language?', 'German', 'Dutch', 'Danish', 'Swedish', 2),
  Q('Words', '“Ciao” is a greeting from which language?', 'Italian', 'Spanish', 'Portuguese', 'Romanian', 2),
  Q('Words', '“Konnichiwa” is hello in which language?', 'Japanese', 'Korean', 'Chinese', 'Thai', 1),
  Q('Words', '“Aloha” is a greeting from where?', 'Hawaii', 'Tahiti', 'Fiji', 'Samoa', 1),
  Q('Words', 'What punctuation mark can join two related sentences?', 'A semicolon', 'A hyphen', 'An ellipsis', 'A slash', 3),
  Q('Words', 'Which punctuation mark shows possession, as in “the frog’s hat”?', 'An apostrophe', 'A comma', 'A dash', 'A tilde', 1),
  Q('Words', 'Which punctuation mark ends an excited sentence?', 'An exclamation mark', 'A period', 'A colon', 'A bracket', 1),
  Q('Words', 'What do you call a person or animal in a story?', 'A character', 'A narrator only', 'A plot', 'A theme', 1),
  Q('Words', 'What do you call the time and place of a story?', 'The setting', 'The plot', 'The moral', 'The climax', 2),
  Q('Words', 'What is a funny play on words called?', 'A pun', 'A limerick', 'A riddle', 'A jingle', 1),
  Q('Words', 'What is a short traditional saying with advice called?', 'A proverb', 'A slogan', 'A chant', 'A motto only', 2),
  Q('Words', 'A made-up story is called what?', 'Fiction', 'Non-fiction', 'Biography', 'Journalism', 1),
  Q('Words', 'A book of true facts is called what?', 'Non-fiction', 'Fiction', 'Fantasy', 'Fable', 1),
  Q('Words', 'The person who draws a book’s pictures is the what?', 'Illustrator', 'Author', 'Editor', 'Publisher', 1),
  Q('Words', 'What is a group of sentences about one idea called?', 'A paragraph', 'A chapter', 'A clause', 'A phrase', 1),
  Q('Words', 'What is the study of word origins called?', 'Etymology', 'Entomology', 'Phonology', 'Grammar', 3),

  // ---------------- NUMBERS ----------------
  Q('Numbers', 'What is 7 × 8?', '56', '54', '64', '48', 1),
  Q('Numbers', 'How many sides does a hexagon have?', 'Six', 'Five', 'Seven', 'Eight', 1),
  Q('Numbers', 'What is half of 90?', '45', '40', '35', '55', 1),
  Q('Numbers', 'The angles of a triangle add up to how many degrees?', '180', '90', '360', '270', 2),
  Q('Numbers', 'Which of these numbers is prime?', '7', '4', '6', '9', 1),
  Q('Numbers', 'What is 12 squared?', '144', '124', '112', '154', 2),
  Q('Numbers', 'How many minutes are in an hour and a half?', '90', '80', '100', '110', 1),
  Q('Numbers', 'What is 25% of 200?', '50', '25', '75', '40', 2),
  Q('Numbers', 'What number does the Roman numeral X represent?', '10', '5', '50', '100', 1),
  Q('Numbers', 'How many sides does an octagon have?', 'Eight', 'Six', 'Seven', 'Ten', 1),
  Q('Numbers', 'What is 100 divided by 4?', '25', '20', '30', '40', 1),
  Q('Numbers', 'Which shape has no corners?', 'Circle', 'Square', 'Triangle', 'Hexagon', 1),
  Q('Numbers', 'What is 9 × 9?', '81', '72', '99', '89', 1),
  Q('Numbers', 'What is 6 × 7?', '42', '36', '48', '54', 1),
  Q('Numbers', 'What is 8 × 8?', '64', '56', '72', '68', 1),
  Q('Numbers', 'What is 15 + 26?', '41', '39', '43', '31', 1),
  Q('Numbers', 'What is 100 − 37?', '63', '67', '73', '53', 2),
  Q('Numbers', 'What is 12 × 11?', '132', '121', '122', '142', 2),
  Q('Numbers', 'What is half of 70?', '35', '30', '40', '45', 1),
  Q('Numbers', 'What is a quarter of 80?', '20', '25', '40', '15', 1),
  Q('Numbers', 'How many sides does a pentagon have?', 'Five', 'Six', 'Four', 'Seven', 1),
  Q('Numbers', 'How many sides does a decagon have?', 'Ten', 'Eight', 'Nine', 'Twelve', 3),
  Q('Numbers', 'What is a triangle with all equal sides called?', 'Equilateral', 'Isosceles', 'Scalene', 'Right', 2),
  Q('Numbers', 'What is the distance around a circle called?', 'Circumference', 'Diameter', 'Radius', 'Perimeter line', 2),
  Q('Numbers', 'What is half of a circle’s diameter called?', 'The radius', 'The chord', 'The arc', 'The tangent', 2),
  Q('Numbers', 'What is pi approximately equal to?', '3.14', '3.41', '2.14', '4.13', 1),
  Q('Numbers', 'What is 10 to the power of 2?', '100', '20', '1000', '12', 2),
  Q('Numbers', 'What is 2 to the power of 5?', '32', '25', '16', '64', 3),
  Q('Numbers', 'What is the next prime number after 7?', '11', '9', '13', '10', 2),
  Q('Numbers', 'What is an angle smaller than 90 degrees called?', 'Acute', 'Obtuse', 'Right', 'Reflex', 2),
  Q('Numbers', 'What is an angle larger than 90 but less than 180 called?', 'Obtuse', 'Acute', 'Straight', 'Reflex', 2),
  Q('Numbers', 'What is an angle of exactly 90 degrees called?', 'A right angle', 'A left angle', 'A flat angle', 'A square angle', 1),
  Q('Numbers', 'What number does the Roman numeral L represent?', '50', '100', '500', '5', 3),
  Q('Numbers', 'What number does the Roman numeral C represent?', '100', '50', '10', '1000', 3),
  Q('Numbers', 'What number does the Roman numeral M represent?', '1000', '100', '500', '50', 2),
  Q('Numbers', 'What number does the Roman numeral V represent?', '5', '10', '4', '50', 1),
  Q('Numbers', 'What is 3/4 written as a percentage?', '75%', '60%', '80%', '34%', 2),
  Q('Numbers', 'What is 0.5 written as a fraction?', 'One half', 'One fifth', 'One quarter', 'Five tenths of a tenth', 1),
  Q('Numbers', 'How many seconds are in a minute?', '60', '100', '30', '90', 1),
  Q('Numbers', 'How many minutes are in a full day?', '1440', '1240', '1640', '2440', 3),
  Q('Numbers', 'How many millimeters are in a centimeter?', '10', '100', '1000', '5', 1),
  Q('Numbers', 'How many centimeters are in a meter?', '100', '10', '1000', '60', 1),
  Q('Numbers', 'How many grams are in a kilogram?', '1000', '100', '10', '500', 1),
  Q('Numbers', 'How many items are in a dozen?', '12', '10', '13', '6', 1),
  Q('Numbers', 'How many items are in a baker’s dozen?', '13', '12', '14', '11', 2),
  Q('Numbers', 'What number comes after a million?', 'A billion', 'A trillion', 'A zillion', 'A milliard only', 1),

  // ---------------- GENERAL ----------------
  Q('General', 'How many days are in a leap year?', '366', '365', '364', '367', 1),
  Q('General', 'Red, yellow and which color are the primary paint colors?', 'Blue', 'Green', 'Purple', 'Orange', 1),
  Q('General', 'How many colors are in a rainbow?', 'Seven', 'Five', 'Six', 'Eight', 1),
  Q('General', 'Which month can have 29 days?', 'February', 'April', 'June', 'November', 1),
  Q('General', 'How many hours are in a day?', '24', '12', '36', '48', 1),
  Q('General', 'Which direction does a compass needle point?', 'North', 'South', 'East', 'West', 1),
  Q('General', 'What is frozen water called?', 'Ice', 'Steam', 'Frost dust', 'Snowmelt', 1),
  Q('General', 'How many sides does a stop sign have?', 'Eight', 'Six', 'Five', 'Ten', 2),
  Q('General', 'Which gas makes party balloons float?', 'Helium', 'Oxygen', 'Hydrogen', 'Nitrogen', 1),
  Q('General', 'How many years are in a century?', '100', '10', '50', '1000', 1),
  Q('General', 'What device measures earthquakes?', 'A seismograph', 'A barometer', 'A telescope', 'A sundial', 2),
  Q('General', 'What do you call a house made of ice blocks?', 'An igloo', 'A yurt', 'A cabin', 'A teepee', 1),
  Q('General', 'How many days are in a fortnight?', '14', '7', '10', '21', 3),
  Q('General', 'Halloween falls in which month?', 'October', 'September', 'November', 'August', 1),
  Q('General', 'Christmas falls in which month?', 'December', 'November', 'January', 'October', 1),
  Q('General', 'Which month starts the new year?', 'January', 'December', 'February', 'March', 1),
  Q('General', 'How many months have 31 days?', 'Seven', 'Six', 'Five', 'Eight', 3),
  Q('General', 'What color do blue and yellow paint make?', 'Green', 'Purple', 'Orange', 'Brown', 1),
  Q('General', 'What color do red and blue paint make?', 'Purple', 'Green', 'Pink', 'Brown', 1),
  Q('General', 'What color do red and yellow paint make?', 'Orange', 'Green', 'Purple', 'Pink', 1),
  Q('General', 'What color do black and white make when mixed?', 'Gray', 'Beige', 'Silver', 'Brown', 1),
  Q('General', 'What does a red traffic light mean?', 'Stop', 'Go', 'Slow down', 'Turn only', 1),
  Q('General', 'How many wheels does a tricycle have?', 'Three', 'Two', 'Four', 'One', 1),
  Q('General', 'How many wheels does a unicycle have?', 'One', 'Two', 'Three', 'Four', 1),
  Q('General', 'Which season comes right after winter?', 'Spring', 'Summer', 'Autumn', 'The wet season', 1),
  Q('General', 'In which season do trees famously drop their leaves?', 'Autumn', 'Spring', 'Summer', 'Winter', 1),
  Q('General', 'What is the hottest season of the year?', 'Summer', 'Spring', 'Autumn', 'Winter', 1),
  Q('General', 'What do you use to look at distant stars?', 'A telescope', 'A microscope', 'A periscope', 'A magnifier', 1),
  Q('General', 'Where do bees live?', 'A hive', 'A nest only', 'A burrow', 'A den', 1),
  Q('General', 'Where does a king or queen traditionally live?', 'A castle', 'A cottage', 'A cabin', 'A villa', 1),
  Q('General', 'What number do you call for emergencies in the USA?', '911', '999', '112 only', '411', 1),
  Q('General', 'How many faces does a cube have?', 'Six', 'Four', 'Eight', 'Twelve', 2),
  Q('General', 'What do you call the person who flies a plane?', 'A pilot', 'A captain only', 'A navigator', 'A steward', 1),
  Q('General', 'What do you call a doctor for teeth?', 'A dentist', 'An optician', 'A surgeon', 'A pediatrician', 1),
  Q('General', 'Who fixes leaking water pipes?', 'A plumber', 'An electrician', 'A mason', 'A welder', 1),
  Q('General', 'What color are most school buses in the USA?', 'Yellow', 'Orange', 'White', 'Blue', 1),
  Q('General', 'Which side of the road do Americans drive on?', 'The right', 'The left', 'Either side', 'The middle', 1),
  Q('General', 'Which country famously drives on the left?', 'The United Kingdom', 'Germany', 'France', 'Spain', 2),
  Q('General', 'What are balls of ice that fall during storms called?', 'Hail', 'Sleet', 'Graupel only', 'Frost', 2),
  Q('General', 'What is the glowing light show near the North Pole called?', 'The northern lights', 'Star rain', 'Sky fire', 'Polar glow', 2),

  // ---------------- HUMAN BODY ----------------
  Q('Human Body', 'How many chambers does the human heart have?', 'Four', 'Two', 'Three', 'Five', 2),
  Q('Human Body', 'Which organ pumps blood around your body?', 'The heart', 'The liver', 'The lungs', 'The kidneys', 1),
  Q('Human Body', 'Which organ do you think with?', 'The brain', 'The heart', 'The spine', 'The stomach', 1),
  Q('Human Body', 'Which organs fill with air when you breathe?', 'The lungs', 'The kidneys', 'The muscles', 'The ears', 1),
  Q('Human Body', 'Which organs filter your blood and make urine?', 'The kidneys', 'The lungs', 'The intestines', 'The spleen only', 2),
  Q('Human Body', 'Which organ uses acid to digest food?', 'The stomach', 'The liver', 'The heart', 'The pancreas', 1),
  Q('Human Body', 'What is the largest bone in the human body?', 'The femur', 'The tibia', 'The spine', 'The humerus', 2),
  Q('Human Body', 'Where is the smallest bone in your body?', 'In the ear', 'In the toe', 'In the finger', 'In the nose', 3),
  Q('Human Body', 'What is the kneecap’s proper name?', 'The patella', 'The fibula', 'The ulna', 'The sternum', 3),
  Q('Human Body', 'How many teeth does a full adult set have?', '32', '28', '30', '36', 2),
  Q('Human Body', 'How many baby teeth do children grow?', '20', '24', '16', '32', 3),
  Q('Human Body', 'What is the hardest substance in the human body?', 'Tooth enamel', 'Bone', 'Cartilage', 'Fingernail', 2),
  Q('Human Body', 'What do red blood cells carry around the body?', 'Oxygen', 'Sugar', 'Water', 'Salt', 1),
  Q('Human Body', 'Which blood cells fight infections?', 'White blood cells', 'Red blood cells', 'Platelets', 'Plasma cells only', 2),
  Q('Human Body', 'What tiny cell fragments help your blood clot?', 'Platelets', 'Neurons', 'Enzymes', 'Antibodies', 3),
  Q('Human Body', 'What is the largest muscle in the human body?', 'The gluteus maximus', 'The biceps', 'The heart', 'The calf', 3),
  Q('Human Body', 'What connects muscles to bones?', 'Tendons', 'Ligaments', 'Nerves', 'Veins', 2),
  Q('Human Body', 'What connects bones to other bones?', 'Ligaments', 'Tendons', 'Muscles', 'Cartilage pads', 3),
  Q('Human Body', 'What is your windpipe called?', 'The trachea', 'The esophagus', 'The larynx', 'The bronchus', 2),
  Q('Human Body', 'What is your voice box called?', 'The larynx', 'The pharynx', 'The trachea', 'The uvula', 3),
  Q('Human Body', 'What tube carries food from your mouth to your stomach?', 'The esophagus', 'The trachea', 'The windpipe', 'The aorta', 2),
  Q('Human Body', 'What is the colored ring of your eye called?', 'The iris', 'The pupil', 'The cornea', 'The retina', 2),
  Q('Human Body', 'What is the black center of your eye called?', 'The pupil', 'The iris', 'The lens', 'The sclera', 1),
  Q('Human Body', 'What part at the back of your eye senses light?', 'The retina', 'The iris', 'The cornea', 'The eyelid', 2),
  Q('Human Body', 'Sight, hearing, taste, touch and which fifth sense?', 'Smell', 'Balance', 'Direction', 'Temperature', 1),
  Q('Human Body', 'How many ribs do most people have?', '24', '20', '28', '32', 3),
  Q('Human Body', 'What is your spine also called?', 'The backbone', 'The tailbone', 'The wishbone', 'The keel', 1),
  Q('Human Body', 'Which bones protect your brain?', 'The skull', 'The ribs', 'The jaw', 'The spine', 1),
  Q('Human Body', 'What cage of bones protects your heart and lungs?', 'The rib cage', 'The pelvis', 'The skull', 'The spine', 1),
  Q('Human Body', 'Which upper-arm bone has a funny-sounding name?', 'The humerus', 'The femur', 'The tibia', 'The radius', 2),
  Q('Human Body', 'What is the dangly thing at the back of your throat called?', 'The uvula', 'The tonsil', 'The epiglottis', 'The adenoid', 2),
  Q('Human Body', 'About what percent of your body is water?', 'About 60%', 'About 30%', 'About 90%', 'About 10%', 2),
  Q('Human Body', 'Do babies have more or fewer bones than adults?', 'More', 'Fewer', 'The same', 'It varies randomly', 3),
  Q('Human Body', 'What is normal human body temperature in Celsius?', '37°C', '35°C', '39°C', '40°C', 2),
  Q('Human Body', 'What is normal human body temperature in Fahrenheit?', '98.6°F', '96.8°F', '100.4°F', '95°F', 2),
  Q('Human Body', 'Which organ makes insulin?', 'The pancreas', 'The liver', 'The spleen', 'The thyroid', 3),
  Q('Human Body', 'What is the largest internal organ?', 'The liver', 'The heart', 'The brain', 'The stomach', 3),
  Q('Human Body', 'Which joint connects your foot to your leg?', 'The ankle', 'The wrist', 'The knee', 'The hip', 1),
  Q('Human Body', 'Which joint connects your hand to your arm?', 'The wrist', 'The elbow', 'The ankle', 'The shoulder', 1),
  Q('Human Body', 'What pigment gives skin its color?', 'Melanin', 'Keratin', 'Carotene only', 'Hemoglobin', 2),
  Q('Human Body', 'Where are your taste buds located?', 'On the tongue', 'On the lips', 'In the throat', 'On the roof of the mouth only', 1),
  Q('Human Body', 'When do you get goosebumps?', 'When cold or scared', 'When hungry', 'When sleepy', 'When dizzy', 1),
];

// --- integrity check: fail fast if the bank is malformed ---
(function validate() {
  const seen = new Set();
  const tally = { 1: 0, 2: 0, 3: 0 };
  for (const q of QUESTIONS) {
    if (!q.text || !q.correct || !Array.isArray(q.wrong) || q.wrong.length !== 3) {
      throw new Error('Malformed question: ' + JSON.stringify(q));
    }
    if (![1, 2, 3].includes(q.d)) throw new Error('Bad difficulty in: ' + q.text);
    const opts = [q.correct, ...q.wrong];
    if (new Set(opts.map(o => String(o).toLowerCase())).size !== 4) {
      throw new Error('Duplicate options in: ' + q.text);
    }
    if (seen.has(q.text.toLowerCase())) throw new Error('Duplicate question: ' + q.text);
    seen.add(q.text.toLowerCase());
    tally[q.d]++;
  }
  QUESTIONS.tally = tally;
})();

module.exports = QUESTIONS;
